### ISSUE TITLE
Parser throws error when parsing a CASE WHEN with space between sum operator

### ISSUE THREAD

**Issue by julio-vaz** [klahnakoski/mo-sql-parsing#100]
Thanks for all the fixes and the effort to make this the best SQL parser!

**The problem** 

Parser does not support space(s) between sum operator (plus sign +) when used in a context of a CASE WHEN clause. This is supported by the parser for a subtraction sign (-).

**How to reproduce?**

This work:

```python
import mo_sql_parsing
sql = """
SELECT
    CASE WHEN 1=1 THEN +1 ELSE - 1 END AS x
FROM
    `a.b.c`
"""
mo_sql_parsing.parse(sql)
```

This does not work:

```python
import mo_sql_parsing
sql = """
SELECT
    CASE WHEN 1=1 THEN + 1 ELSE - 1 END AS x
FROM
    `a.b.c`
"""
mo_sql_parsing.parse(sql)
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/d47f710b5a769bf507b2b693962832140f333f59

but compilation is now 1/2 as fast.  hmm.

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.191.22203/
