### ISSUE TITLE
Temporary and transient tables

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#101]
The following statements fail to parse.

1. Some databases (e.g. Snowflake) allow TEMP instead of TEMPORARY
```
CREATE TEMP TABLE foo(a varchar(10))
```
2. Snowflake has transient tables and allows this:
```
CREATE TRANSIENT TABLE foo(a varchar(10))
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/494d8a3f73d5e5176b4dc5183d0e442dbacdaff5

**Comment by leo-fmr** [comment]
Wow, that was fast! 😊

Transient actually has different meaning than temporary so it should probably end up in a separate property.


From: Kyle Lahnakoski ***@***.***>
Date: Wednesday, August 17, 2022 at 5:35 PM
To: klahnakoski/mo-sql-parsing ***@***.***>
Cc: Braginsky, Leonid ***@***.***>, Author ***@***.***>
Subject: Re: [klahnakoski/mo-sql-parsing] Temporary and transient tables (Issue #101)
NOTICE: This email is from an external sender - do not click on links or attachments unless you recognize the sender and know the content is safe.


494d8a3<https://github.com/klahnakoski/mo-sql-parsing/commit/494d8a3f73d5e5176b4dc5183d0e442dbacdaff5>

**Comment by klahnakoski** [comment]
fixing test here: https://github.com/klahnakoski/mo-sql-parsing/commit/f69b1f127e8033b5cb610a0ec108a47cdcd3634b#diff-a82d1c3ecd7beb06662cb47f78ded43cab653a0759ef98153d3b961d149a974cL36

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.194.22230/
