### ISSUE TITLE
Table functions

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#102]
Snowflake supports table functions, e.g.
```
SELECT seq4()
FROM TABLE(generator(rowcount => 10))
```
A couple more examples:
```
SELECT uniform(1, 10, random())
FROM TABLE(generator(rowcount => 5));
```
```
SELECT t.index, t.value
FROM TABLE(split_to_table('a.b.z.d', '.')) as t
ORDER BY t.value;
```
Snowflake table functions are documented here: https://docs.snowflake.com/en/sql-reference/functions-table.html

**Comment by klahnakoski** [comment]
well, `rowcount => 10` is interesting; I would have expected `>=`, not `=>`.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/e808b70bd77277227ca50603136c26514115746a

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.194.22230/

**Comment by leo-fmr** [comment]
The => in rowcount => 5 is not a GE comparison operator. I could not find what they call it in Snowflake documentation but it is roughly equivalent to Python's '=' in keyword argument specification.

**Comment by klahnakoski** [comment]
looking....

**Comment by klahnakoski** [comment]
@leo-fmr   thank you!  it would appear this is a way to provide keyword parameters to function calls.  Still not sure though.

https://docs.snowflake.com/en/sql-reference/functions/generator.html

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/34060e3693d4454fa3af4b0cec76f1679e153ca7

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.195.22230/

**Comment by leo-fmr** [comment]
@klahnakoski The => is used for passing keyword arguments in many other functions , e.g.
https://docs.snowflake.com/en/sql-reference/functions/flatten.html
https://docs.snowflake.com/en/sql-reference/functions/copy_history.html
etc.
