### ISSUE TITLE
Some text types fail to parse

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#104]
Both of these statements fail to parse:
```
CREATE TABLE foo(a CHARACTER(5))
CREATE TABLE foo(a CHARACTER VARYING(5))
```
CHARACTER and CHARACTER VARYING are the official type names from the ANSI SQL standard, CHAR and VARCHAR are their respective short aliases.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/29b931b6f67d786ba4d9e8fa6522244820f397a3

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.195.22230/
