### ISSUE TITLE
Multi-line string literals

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#105]
This query fails to parse:
```
SELECT 'one
two
three'
FROM my_table
```
This works in many databases including MySql, Postgres, Snowflake and others.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/6a1d528eb5b146d904512bd2655fe434be3cb28d

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.195.22230/
