### ISSUE TITLE
Column named "index"

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#106]
Both of these queries fail to parse:
```
SELECT index FROM my_table;
CREATE TABLE my_table(index INTEGER);
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/33bd9c8caae4245123fb016761affd50c9566ae1

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.197.22232/
