### ISSUE TITLE
lateral join with function call

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#107]
Suppose we have this `employees` table in which `project_names` is an array-valued column.
```
EMPLOYEE_ID LAST_NAME   PROJECT_NAMES
101         Richards    ["Materialized Views", "UDFs"]
102         Paulson     ["Materialized Views", "Lateral Joins"]
```
In the following query the inline view for the lateral join comes from a function call, in this case the `flatten` function.
```
SELECT emp.employee_id, emp.last_name, value AS project_name
FROM employees AS emp, LATERAL flatten(input => emp.project_names) AS proj_names
ORDER BY employee_id;
```
It fails with
```
Expecting (, found "flatten(in" (at char 93), (line:3, col:32)
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/cfe1dd9d107d1035cb28575458733230d7d18613

**Comment by klahnakoski** [comment]
the flatten function parses to:

     {"flatten": {}, "input": "emp.project_names"}

if this is a problem, then use `parse(sql, calls=normal_op)` which will provide keyword parameters in `kwargs` (and regular parameters in `args`).

    {
         'op': 'flatten',
         'kwargs': {'input': 'emp.project_names'}
    }

**Comment by klahnakoski** [comment]
one test changed.  I am considering if it is important:

                {"lateral": {
                    "name": "iv2",
                    "value": {"from": "employees", "select": "*"},
                }},

was

                {
                    "name": "iv2",
                    "value": {"lateral": {"from": "employees", "select": "*"}},
                },

which makes me think: Is "lateral" a property of the join, or a modification to a table_source?

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.197.22232/

**Comment by leo-fmr** [comment]
Lateral is a type of join that involves outer and inner tables.
There is a decent explanation here: https://www.geeksforgeeks.org/lateral-keyword-in-sql/


From: Kyle Lahnakoski ***@***.***>
Date: Friday, August 19, 2022 at 10:19 PM
To: klahnakoski/mo-sql-parsing ***@***.***>
Cc: Braginsky, Leonid ***@***.***>, Author ***@***.***>
Subject: Re: [klahnakoski/mo-sql-parsing] lateral join with function call (Issue #107)
NOTICE: This email is from an external sender - do not click on links or attachments unless you recognize the sender and know the content is safe.


one test changed. I am considering if it is important:

            {"lateral": {

                "name": "iv2",

                "value": {"from": "employees", "select": "*"},

            }},

was

            {

                "name": "iv2",

                "value": {"lateral": {"from": "employees", "select": "*"}},

            },

which makes me think: Is "lateral" a property of the join, or a modification to a table_source?
