### ISSUE TITLE
Querying Semi-structured Data

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#108]
Snowflake allows columns with semi-structured data (variant type), not sure about other databases.

These queries with variant src column fail to parse:
```
SELECT src:dealership
    FROM car_sales
```
```
SELECT src:salesperson.name
    FROM car_sales
```
There are explanations and other examples here: https://docs.snowflake.com/en/user-guide/querying-semistructured.html

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/e168f0e4987d15bfadc8d34b7766e5f01fbfe8d3

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.199.22240/
