### ISSUE TITLE
Queries with QUALIFY construct

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#109]
These queries with QUALIFY fail to parse:
```
SELECT id, row_number() OVER (PARTITION BY id ORDER BY id) AS row_num
FROM my_table
QUALIFY row_num = 1
```
```
SELECT id, names
FROM my_table
QUALIFY ROW_NUMBER() OVER (PARTITION BY id ORDER BY id) = 1
```
Snowflake documentation for QUALIFY is here: https://docs.snowflake.com/en/sql-reference/constructs/qualify.html

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/979ed199e462ebdcc5fe3b236ac3613554f9a17f

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.199.22240/
