### ISSUE TITLE
Problem with query containing a '"' string

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#110]
This query fails to parse:
```
SELECT REPLACE(foo, '"', '') AS bar
FROM my_table
```
Interestingly, this one succeeds:
```
SELECT REPLACE(foo, 'x', '') AS bar
FROM my_table
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/62c98113d1b8a4316f0029ffe8efa20cfce5fe18

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.199.22240/

**Comment by klahnakoski** [comment]
thank you for this!
