### ISSUE TITLE
Query containing ILIKE matching

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#111]
This query fails:
```
SELECT * 
    FROM my_table 
    WHERE subject ILIKE '%j%do%'
```
Snowflake allows ILIKE which unlike the LIKE is case sensitive.

Documentation is here: https://docs.snowflake.com/en/sql-reference/functions/ilike.html

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/71d65b09256bb3ce469d34a152d1e2d4da1fc7fd

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.199.22240/
