### ISSUE TITLE
Error parsing UNPIVOT

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#117]
Queries with UNPIVOT fail to parse, e.g.
```
SELECT * FROM monthly_sales
    UNPIVOT(sales for month in (jan, feb, mar, april))
```
Snowflake documentation and example: https://docs.snowflake.com/en/sql-reference/constructs/unpivot.html

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/886a0c522594d3c6468e0c37d13c4947bc05e0d6

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.201.22242/
