### ISSUE TITLE
Error parsing ALTER SESSION commands

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#118]
Examples:
```
ALTER SESSION SET TIMESTAMP_TYPE_MAPPING = TIMESTAMP_NTZ
```
```
ALTER SESSION SET LOCK_TIMEOUT = 3600
```
```
ALTER SESSION UNSET LOCK_TIMEOUT
```
Snowflake documentation: https://docs.snowflake.com/en/sql-reference/sql/alter-session.html

There are many other ALTER commands, all of them do not parse, e.g.
```
ALTER TABLE my_table RENAME TO their_table
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/9fdd0e20cd442ec515cdd9e93413c0b1e763f37e

added  https://github.com/klahnakoski/mo-sql-parsing/issues/120

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.201.22242/
