### ISSUE TITLE
Error parsing COPY commands

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#119]
This is a huge can of worms :)

Snowflake supports COPY INTO commands for copying data between tables and external storage both ways.
Snowflake documentation is here: 
https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html
https://docs.snowflake.com/en/sql-reference/sql/copy-into-location.html

Postgres also supports COPY commands with different syntax.
Postgres documentation is here:
https://www.postgresql.org/docs/current/sql-copy.html

**Comment by klahnakoski** [comment]
Yes, many worms.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/3b8d0caa0cbd24bdeebfa02b48a7d5f44dd1cb29

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/f675a97ac3d1c0ec985f7d6fcb2f6e3c4df7566e

**Comment by klahnakoski** [comment]
Moved additional work to https://github.com/klahnakoski/mo-sql-parsing/issues/122

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.202.22245/
