### ISSUE TITLE
Parser does not support BigQuery's DECLARE clause

### ISSUE THREAD

**Issue by lveras** [klahnakoski/mo-sql-parsing#123]
When parsing queries that contains a call to [DECLARE clause](https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#declare) the parser raises an exception.

How to reproduce?

Sample query:

```
DECLARE _current_timestamp timestamp DEFAULT current_timestamp();
    DECLARE _current_date      date      DEFAULT current_date("America/Sao_Paulo");

    CREATE TEMP TABLE all_movements AS
        SELECT 
            confirmed_transaction_id
            , id_movement
            , cast(case when mov.operation_code = 1 then mov.amount else -mov.amount end as BIGNUMERIC) as amount
            , mov.due_date
        FROM `dataplatform-treated-non-prod.src_acquirer_core.client_fin_movement__movements` mov  
            WHERE CAST(entry_date as date) > "2020-12-01" AND movement_category IN (14, 24, 25, 28);
```

Exeption:
```Expecting {query} | {delete}, found "DECLARE _c" (at char 0), (line:1, col:1)```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/a16fccfb544989fd2e12f135a18c71d078d8bac1

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.204.22252/
