### ISSUE TITLE
pivot and unpivot as identifier/alias cause issues

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#125]
With the latest release, queries that are using `pivot` or `unipivot` started to fail parsing. For instance:

```sql
SELECT * FROM pivot;
SELECT * FROM a AS pivot;
SELECT * FROM UNNEST(ARRAY[1, 2, 3]) AS pivot(n);
SELECT * FROM UNNEST(ARRAY[1, 2, 3]) AS pivot(n)
  JOIN a ON a.id = pivot.n;
```
Same for `unpivot`. Those queries would run on PrestoDB/Athena. I understand that you added support for those keywords in languages where they are special functions. Would it be possible to keep supporting them as identifiers as well?

Thanks

**Comment by klahnakoski** [comment]
thank you for this.  fixing....

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/4c0e7124bbcac7e5827f2575a5be45997a79e038

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.204.22252/

**Comment by sbrandtb** [comment]
Thanks!
