### ISSUE TITLE
lateral view SQL clause

### ISSUE THREAD

**Issue by nancy-zwx** [klahnakoski/mo-sql-parsing#126]
it can not support "lateral view" SQL clause, I think it would be  a great help if it can be fixed

**Comment by klahnakoski** [comment]
The best I can tell, lateral view is supported.  Do you have an example?  I will try to find a breaking example.

**Comment by nancy-zwx** [comment]
Hi,
Yes, it is supported. I'm sorry to interrupt you.&nbsp;
I'm new to SQL. I was trying to parse a somewhat complex sql and I typed these lines:


from mo_sql_parsing import parse
result=parse ("SELECT algid, item_id, avg(score) as avg_score from (select ds, algid, uin, split(item_result, ":")[0] as item_id, split(item_result, ":")[1] as score from (select ds, scorealgid_ as algid, uin_ as uin, item_result from (select * from t_dwd_tmp_wxpay_discount_model_score_hour where ds &gt;= 2022080300 and ds <= 2022080323)day_tbl LATERAL VIEW explode(split(scoreresult_, "\\|")) temp AS item_result)t)tbl group by algid, item_id;")
print(result)



and there seems an issue at " LATERAL VIEW explode(split(scoreresult_, "\\|"))"


then I changed the format as:
&nbsp; &nbsp; sql='''
&nbsp; &nbsp; SELECT algid, item_id, avg(score) as avg_score from (select ds, algid, uin, split(item_result, ":")[0] as item_id, split(item_result, ":")[1] as score from (select ds, scorealgid_ as algid, uin_ as uin, item_result from (select * from t_dwd_tmp_wxpay_discount_model_score_hour where ds &gt;= 2022080300 and ds <= 2022080323)day_tbl LATERAL VIEW explode(split(scoreresult_, "\\|")) temp AS item_result)t)tbl group by algid, item_id;
&nbsp; &nbsp; '''
&nbsp; &nbsp; result=parse (sql)



and it worked. I didn't figure out the reason. Could you please tell me why it is the case? Many thanks!!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "klahnakoski/mo-sql-parsing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月13日(星期二) 晚上8:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [klahnakoski/mo-sql-parsing] lateral view SQL clause (Issue #126)





 
The best I can tell, lateral view is supported.  Do you have an example?  I will try to find a breaking example.

**Comment by klahnakoski** [comment]
@nancy-zwx 

It is  hard for me to run your code;  There is a lot of html encoding in it.  If I convert to plain text then I get:

      from mo_sql_parsing import parse

      result = parse(
          """SELECT algid, item_id, avg(score) as avg_score 
          from (
              select 
                  ds, 
                  algid, 
                  uin, 
                  split(item_result, ":")[0] as item_id, 
                  split(item_result, ": ")[1] as score 
              from (
                  select ds, scorealgid_ as algid, uin_ as uin, item_result 
                  from (
                      select * 
                      from t_dwd_tmp_wxpay_discount_model_score_hour 
                      where ds >= 2022080300 and ds <= 2022080323
                  ) day_tbl 
                  LATERAL VIEW explode(split(scoreresult_, "\\ | ")) temp AS item_result
              ) t
          ) tbl 
          group by algid, item_id;"""
      )

which parses fine (but wrong).  Maybe you still have html in it?

I noticed that you have double-quotes in the SQL for literal strings.  You must be parsing MySql.  Be sure to use the mysql version of the parser:

    from mo_sql_parsing import parse_mysql as parse
