### ISSUE TITLE
Failure to parse UPDATE with aliased table

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#127]
The following query fails to parse:
```
UPDATE my_table a
SET flag = 1
FROM source_table s
WHERE a.name = s.name
```
```
Expecting set, found "a\nSET flag" (at char 17), (line:2, col:17)
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/7981cfcfe1d1f245a103bf2ac691412091b2eb47

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/7981cfcfe1d1f245a103bf2ac691412091b2eb47

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.205.22260/
