### ISSUE TITLE
SUBSTRING(input_string from num1 for num2) not support

### ISSUE THREAD

**Issue by likun1234** [klahnakoski/mo-sql-parsing#128]
![image](https://user-images.githubusercontent.com/37656757/194736811-5ee2501d-463f-41c1-8031-76a151301f9d.png)
Traceback (most recent call last):
  File "parser/sql_parsing.py", line 583, in <module>
    print(parse(sql25))
  File "mo_sql_parsing\__init__.py", line 37, in parse
    result = _parse(common_parser, sql, null, calls)
  File "mo_sql_parsing\__init__.py", line 78, in _parse
    parse_result = parser.parse_string(SQL, parse_all=True)
  File "mo_parsing\core.py", line 80, in output
    return func(*args, **kwargs)
  File "mo_parsing\core.py", line 149, in parse
    return self._parseString(string, parse_all=parse_all)
  File "mo_parsing\core.py", line 171, in _parseString
    raise cause.best_cause from None
mo_parsing.exceptions.ParseException: Expecting ), found "(c_phone f" (at char 164), (line:9, col:34)

**Comment by klahnakoski** [comment]
thank you for submitting this.  Let me find what database supports this syntax ....

**Comment by klahnakoski** [comment]
https://www.w3resource.com/PostgreSQL/substring-function.php

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/ff25b243e84ad0b85fbcc47843c82f8fbc011a7c

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.207.22283/
