### ISSUE TITLE
wether mo-sql-sparing can parser 'insert into' or not

### ISSUE THREAD

**Issue by 813BoZai** [klahnakoski/mo-sql-parsing#131]
I need to parser some sql about DML and DDL

**Comment by klahnakoski** [comment]
Please give it a try.  You have an example?

**Comment by 813BoZai** [comment]
insert into datajoin.dw_application_barsl_count_base(creation_date,
lb_code,
lb_name,
application_id,
barcode,
org_code,
customer_id,
customer_code,
customer_name,
dock_type,
dock_name,
barsl,
jointbarsl,
unjointsl)
select t.creation_date,t.sub_code,t.sub_name,t.application_id,t.barcode,t.org_code,t.customer_id,t.customer_code,t.customer_name,t.dock_type,t.dock_name,sum(t.sumbarsl) as barsl,sum(t.sumjointbarsls) as jointbarsl,sum(t.unjointsl) as unjointsls from
(select  v.creation_date,s.sub_code,s.sub_name,v.application_id,v.barcode,v.org_code,v.customer_id,v.customer_code,c.customer_name,appk.dock_type,appk.dock_name,v.sumbarsl,u.sumjointbarsls,((case when v.sumbarsl is null then 0 else v.sumbarsl end) - (case when u.sumjointbarsls is null then 0 else u.sumjointbarsls end)) as unjointsl  
from datajoin.dw_application_joint_base v
left join datajoin.dw_application_upload_op_union_group_base u on v.application_id=u.application_id
left join datajoin.dw_application_dock_base_v appk on v.application_id=appk.application_id
inner join datajoin.ms_customer_info_v c on v.customer_code=c.customer_code  
inner join kmcsdw.sub_com_org s on substr(v.org_code,0,5)=s.sub_code
) t
group by  t.creation_date,t.sub_code,t.sub_name,t.application_id,t.barcode,t.org_code,t.customer_id,t.customer_code,t.customer_name,t.dock_type,t.dock_name;

**Comment by 813BoZai** [comment]
like this my code is:
import sys
sys.setrecursionlimit(3000)
import json
import moz_sql_parser 

print(moz_sql_parser.parse(sql))
print(type(kl))

**Comment by 813BoZai** [comment]
oh！I am using the moz_sql_parser not mo-sql-parsing.Now I am successful  parsing the sql  about 'insert into'
