### ISSUE TITLE
Not support syntax like this: interval ':1' day (3)

### ISSUE THREAD

**Issue by likun1234** [klahnakoski/mo-sql-parsing#134]
When SQL contains syntax like this，
![image](https://user-images.githubusercontent.com/37656757/200160582-522bbe66-5658-4087-b89d-dc0131b20d27.png)
the parse function produces the following error:
![image](https://user-images.githubusercontent.com/37656757/200160645-f4565552-3489-44e3-8408-cc533282ca9d.png)
When modified to the following syntax, the error disappears：
![image](https://user-images.githubusercontent.com/37656757/200160560-3f49c9df-6590-4b40-b296-977db5be7881.png)

**Comment by klahnakoski** [comment]
https://www.oracletutorial.com/oracle-basics/oracle-interval/

**Comment by klahnakoski** [comment]
https://www.postgresql.org/docs/9.1/functions-datetime.html

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/37318a23a89ab6011f5100b583df71c732e1bc45

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.236.22315/
