### ISSUE TITLE
format for delete from syntax

### ISSUE THREAD

**Issue by guoguozhenhaowan** [klahnakoski/mo-sql-parsing#137]
![image](https://user-images.githubusercontent.com/22541102/200785429-ccf8e9f0-fc6b-4d26-91d2-9b06790c1096.png)

**Comment by klahnakoski** [comment]
yes, the DML formatting is quite limited.

**Comment by klahnakoski** [comment]
I will look into this tomorrow

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/a482855c709fb8042f16075c8c8be685ed2a193e

there is a lot of DML commands left to go

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.236.22315/
