### ISSUE TITLE
hiHow to solve the question about 

### ISSUE THREAD

**Issue by 813BoZai** [klahnakoski/mo-sql-parsing#138]

**Comment by 813BoZai** [comment]
the problem likes 'found "t\n  group " (at char 966), (line:16, col:10)',thew picture of worry likes. I am wanting to parse the sql about "  insert into datajoin.dw_application_joint_base(creation_date,
application_id,
barcode,
org_code,
customer_id,
customer_code,
sumbarsl)
 select t.send_day,t.application_id,t.barcode,t.org_code,t.customer_id,t.customer_code,sum(sum_barsl) as sumbarsl from 
	 (select app.creation_date,date_trunc('day', app.creation_date) as send_day,app.application_id,app.barcode,app.biz_org_code as org_code,app.customer_id,SUBSTR(app.collection_location,1,instr(app.collection_location, '|', -1) - 1) as customer_code,1 as sum_barsl	   from  lb.lb_application app
	  where  app.creation_date >= TO_DATE('2020-01-01 00:00:00', 'yyyy-mm-dd HH24:mi:ss'            and app.deleted_flag = '0'
            and not exists (select 1 from datajoin.ods_kmcs_lb_os_internal oi
                where app.application_id = oi.to_id
                and oi.OS_INTERNAL_ID IS NOT NULL
                and oi.deleted_flag = '0'
                and oi.rel_object_table = 'LB_APPLICATION')
	      ) t
  group by t.send_day,t.application_id,t.barcode,t.org_code,t.customer_id,t.customer_code;

"

**Comment by 813BoZai** [comment]
thank you!

**Comment by klahnakoski** [comment]
I will look into this tomorrow

**Comment by klahnakoski** [comment]
the SQL is wrong:

your last two lines should be swapped.  instead of  

```
and oi.rel_object_table = 'LB_APPLICATION')
) t
group by t.send_day,t.application_id,t.barcode,t.org_code,t.customer_id,t.customer_code;
```

you should have

```
and oi.rel_object_table = 'LB_APPLICATION')
group by t.send_day,t.application_id,t.barcode,t.org_code,t.customer_id,t.customer_code
) t
```

I cut-and-pasted your SQL to http://poorsql.com/ ; it shows the problem is at `t\n group`, just like this parser says.
