### ISSUE TITLE
The interval syntax support is not comprehensive enough

### ISSUE THREAD

**Issue by guoguozhenhaowan** [klahnakoski/mo-sql-parsing#147]
like interval '1'
https://www.postgresql.org/docs/current/datatype-datetime.html

**Comment by klahnakoski** [comment]
i am working on this

**Comment by klahnakoski** [comment]
that simple case has been fixed, but a number of others need work  https://pypi.org/project/mo-sql-parsing/9.302.22350/

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.303.22352/
