### ISSUE TITLE
FILTER disappears in format()

### ISSUE THREAD

**Issue by ronnix** [klahnakoski/mo-sql-parsing#148]
Hello,

We just noticed that `FILTER` clauses would disappear during formating:
```python
>>> from mo_sql_parsing import parse, format
>>> query = {"select": {
...             "filter": {"eq": [1, 1]},
...             "name": "foo",
...             "value": {"max": 1},
...         }}
>>> expected = """SELECT MAX(1) FILTER (WHERE 1=1) AS foo"""
>>> format(query)
'SELECT MAX(1) AS foo'
```

Looks like this is related to https://github.com/klahnakoski/mo-sql-parsing/issues/58

We’re happy to try working on a fix, but are not yet familiar with the code base, so we would appreciate some guidance.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/37d37e09174b43348ec9b0b57f05f0b92b966808

**Comment by klahnakoski** [comment]
Thank you very much for submitting an issue!  

https://pypi.org/project/mo-sql-parsing/9.305.22354/

**Comment by ronnix** [comment]
Thanks for the quick fix!
