### ISSUE TITLE
Exception while use STRUCT in BQ

### ISSUE THREAD

**Issue by lveras** [klahnakoski/mo-sql-parsing#150]
Hi!

We recept this error when run sample below.
`mo_parsing.exceptions.ParseException: Expecting expr, found "STRUCT\n   " (at char 10), (line:1, col:11)`

```
SELECT AS STRUCT
    CASE
        WHEN ee.babala = TRUE THEN 'avisos'
        ELSE NULL
    END AS bot_name,
    ee.avisos AS estagio,
    SAFE_CAST(NULL AS STRING) AS demanda,
    SAFE_CAST(NULL AS STRING) AS transfere,
    SAFE_CAST(NULL AS STRING) AS segurana,
    SAFE_CAST(NULL AS BOOLEAN) AS jacson
```

**Comment by klahnakoski** [comment]
That looks interesting.  Let me find some docs on this form...

**Comment by klahnakoski** [comment]
https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_as_struct

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/245feb0e8547e4d627f9076b11e9345f86070dab#diff-028acb5a76624487a6dfd257ba58d641b4a84b95750894e2d5e0e9005032c7f3R611

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.306.22357/
