### ISSUE TITLE
BQ -> lib doesn't recognize MILLISECOND in TIMESTAMP_SUB function

### ISSUE THREAD

**Issue by lveras** [klahnakoski/mo-sql-parsing#154]
Hi!

MILLISECOND parameter isn't recognized for TIMESTAMP_SUB function.

Error: `mo_parsing.exceptions.ParseException: Expecting {ago} | {time_interval_type} | {ilike} | {order} | {limit} | {ago} | {time_interval_type} | {ilike} | {order} | {limit} | {ago} | {time_interval_type} | {ilike} | {order} | {limit} | {ago} | {time_interval_type} | {ilike} | {order} | {limit} | {ago} | {time_interval_type} | {ilike} | {order} | {limit} | {ago} | {time_interval_type} | {ilike} | {order} | {limit} | {ago} | {time_interval_type} | {ilike} | {order} | {limit} | {ago} | {time_interval_type} | {ilike} | {order} | {limit}, found "ILLISECOND" (at char 110), (line:6, col:48)`

Sample:
```
SELECT
    DISTINCT
    m AS mesa,
    COALESCE(
        LEAD(
            TIMESTAMP_SUB(systema, INTERVAL 1 MILLISECOND)
        ) OVER (PARTITION BY id ORDER BY systema ASC),
        TIMESTAMP('9999-12-31 23:59:59.999')) AS end_at,
    airflow_metad AS synced_at
FROM
    `projeto.dataset.tabela` TABLESAMPLE SYSTEM (0.1 PERCENT)
QUALIFY ROW_NUMBER() OVER (PARTITION BY id, systema) = 1
LIMIT 50000
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/54125561b8c8cab92c18980795a01632f7654475

**Comment by klahnakoski** [comment]
pip install mo-sql-parsing==9.327.22363
