### ISSUE TITLE
BigQuery allow trailing commas at the end of a SELECT column list

### ISSUE THREAD

**Issue by lveras** [klahnakoski/mo-sql-parsing#155]
Hi!

BigQuery allow trailing commas at the end of a SELECT column list.

Documentation: https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#trailing_commas

Error: `mo_parsing.exceptions.ParseException: Expecting expression, found "FROM workd" (at char 116), (line:5, col:1)`

Sample:
```
SELECT
    a.day AS src,
    b.day as tgt,
    ROW_NUMBER() OVER(PARTITION BY a.day ORDER BY b.day) - 1 AS qtde_wd,
FROM workdays a
join workdays b ON a.day <= b.day
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/18b5dd67fbe50cfa767b16256968af9881eabc87

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.328.23003/
