### ISSUE TITLE
EXPLAIN queries raise ParseException

### ISSUE THREAD

**Issue by rbergm** [klahnakoski/mo-sql-parsing#157]
Hi Kyle,

I just noticed another parser issue. When faced with [`EXPLAIN`](https://www.postgresql.org/docs/current/using-explain.html) queries, a `ParseException` is raised: 

```python
>>> parse("EXPLAIN SELECT * FROM foo, bar WHERE id = fkey")
ParseException: expecting one of ["(", "alter", "cache", "copy", "create", "declare", "delete", "drop", "insert", "select", "set", "unset", "update", "values", "with"] (), found "EXPLAIN SE" (at char 0), (line:1, col:1)
```

The same applies to more advanced usage scenarious such as `EXPLAIN ANALYZE` supported by Postgres, or `EXPLAIN` with an output format as supported by MySQL and Postgres (at least):

```python
>>> parse("EXPLAIN (ANALYZE, FORMAT JSON) SELECT * FROM foo, bar WHERE id = fkey")
ParseException: expecting one of ["(", "alter", "cache", "copy", "create", "declare", "delete", "drop", "insert", "select", "set", "unset", "update", "values", "with"] (), found "EXPLAIN (A" (at char 0), (line:1, col:1)
```

The precise syntax of this statement as well as the output type vary heavily from system to system, but here is what I found for some common database systems:

- Postgres uses `EXPLAIN` followed by optional `ANALYZE` parameters. If multiple parameters are present, they are wrapped in braces ([link to documentation](https://www.postgresql.org/docs/current/sql-explain.html)).
- MySQL uses `EXPLAIN`, `DESCRIBE` or `DESC` which are all synonymous, followed by an optional `ANALYZE` and an optional format modifier ([link to documentation](https://dev.mysql.com/doc/refman/8.0/en/explain.html))
- MS SQL Server uses `EXPLAIN` followed by an optional `WITH_RECOMMENDATIONS` ([link to documentation](https://learn.microsoft.com/en-us/sql/t-sql/queries/explain-transact-sql))
- Oracle uses `EXPLAIN PLAN` followed by an optional name and table where the plan should be stored. The entire statement seems to be terminated by a `FOR`, which is then followed by the actual query ([link to documentation](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/EXPLAIN-PLAN.html))
- SQLite uses `EXPLAIN` or `EXPLAIN QUERY PLAN`, without any options ([link to documentation](https://www.sqlite.org/lang_explain.html))

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/a58ce3ccec65e3bd16ba17e5ef95ae3be4b25daa#diff-c27809480953c5908cdc63856a3e545a7fd67d739492c0968b61f5090a107b0cR516

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.350.23032/

**Comment by klahnakoski** [comment]
found another https://github.com/klahnakoski/mo-sql-parsing/commit/2bbee0b85a57e6c648357b90031ca64f3750b972#diff-3f3c8e171ca0635eaadb40bf6ea260d38d735529b7bedde4c3ac5f8bd07069e1R46

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.351.23032/

**Comment by klahnakoski** [comment]
@rbergm   Thank you very much for those links.  I hope this covers your use cases.

**Comment by rbergm** [comment]
This is great, thank you very much!
