### ISSUE TITLE
Substring formatting fails when substring does not contains from  in it 

### ISSUE THREAD

**Issue by rostykob** [klahnakoski/mo-sql-parsing#158]
Hello,

I've discovered a bug where query formatting fails when there is a substring used without from for section

Example query 
---
`SELECT CASE WHEN a.attr1 IS NULL THEN CONCAT(SUBSTRING(CONVERT(char(7), attr2 + 1000000), 2, 6), SUBSTRING(CONVERT(char(8), attr3 + 10000000), 2, 7)) ELSE a.attr1 END as alias1 FROM schema.table a`

Error: Key 'from' does not exist  in  json.

I've located issue and will add a pr with fix

**Comment by klahnakoski** [comment]
I see your PR.  Let me make a test too...

**Comment by klahnakoski** [comment]
..looks great!  Thank you!   https://pypi.org/project/mo-sql-parsing/9.352.23038/
