### ISSUE TITLE
No recognizing "from last_modified_date" in BQ

### ISSUE THREAD

**Issue by lveras** [klahnakoski/mo-sql-parsing#163]
Hi!

We found this error when run sample query in BQ.
`mo_parsing.exceptions.ParseException: Expecting {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit}, found "from last_" (at char 37), (line:2, col:31)`

Sample:

```
SELECT
    REPLACE(CAST(EXTRACT(date from last_modified_date at time zone 'America/Sao_Paulo') AS STRING),'-','') as last_modified_date
FROM
    territory2

```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/fe7a7dae15a905b58866e52c469e52001102e147

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.356.23062/
