### ISSUE TITLE
Not recognizing line break after FROM in BQ

### ISSUE THREAD

**Issue by lveras** [klahnakoski/mo-sql-parsing#164]
Error:
`mo_parsing.exceptions.ParseException: Expecting {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit} | {literal_string} | {filter} | {order} | {limit}, found "FROM\n     " (at char 112), (line:6, col:21)`

Sample:

```
SELECT
        REPLACE(
            cast(
                extract(
                    date
                    FROM
                        last_login_date AT TIME ZONE 'America/Sao_Paulo'
                ) AS STRING
            ),
            '-',
            ''
        ) AS last_login_date,
        REPLACE(
            cast(
                extract(
                    date
                    FROM
                        last_modified_date AT TIME ZONE 'America/Sao_Paulo'
                ) AS STRING
            ),
            '-',
            ''
        ) AS last_modified_date,
        REPLACE(
            cast(
                extract(
                    date
                    FROM
                        last_viewed_date AT TIME ZONE 'America/Sao_Paulo'
                ) AS STRING
            ),
            '-',
            ''
        ) AS last_viewed_date,
    FROM
        user u

```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/fe7a7dae15a905b58866e52c469e52001102e147

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.356.23062/
