### ISSUE TITLE
No recognizing  "SELECT AS " in BQ

### ISSUE THREAD

**Issue by MagdaSousa** [klahnakoski/mo-sql-parsing#165]
Hi!

We find this error when running a query like the below in BQ.
mo_parsing.exceptions.ParseException: Expecting {from} | {order} | {offset} | {fetch} | {limit} | {for} | {limit} | {as} | {from} | {order} | {offset} | {fetch} | {limit} | {for} | {limit} | {as}, found "SELECT AS " (at char 298), (line:14, col:2)

sample : 
```
SELECT
   ee.a_id AS id,
   CASE
    WHEN ee._id = 'flow2222222222222' THEN 'flow 2'
    WHEN ee._id = 'flow1111111111111' THEN 'flow 1'
    ELSE NULL
    END AS flow_name,
    array(SELECT AS STRUCT CASE
                        WHEN ee.step_started = TRUE THEN 'avisos'ELSE NULL END AS step_name,
                        ee.ws_status AS ws_status,
                        UNION ALL
                        SELECT AS STRUCT CASE
                        WHEN ee.dg_step_started = TRUE THEN 'dg' ELSE NULL END AS dg_step,
                        ee.dg_status AS dg_status,
                        CASE WHEN cf.demand_informed = TRUE THEN 'informed'
                        WHEN cf.demand_informed = FALSE THEN ' not informed' ELSE NULL END AS description,
                        CASE WHEN cf.verification = TRUE THEN TRUE
                        WHEN cf.verification = FALSE THEN TRUE
                        WHEN cf.contact = TRUE THEN TRUE
                        WHEN cf.verification_sent = FALSE THEN FALSE ELSE NULL END AS verification_sent,
                        UNION ALL SELECT AS STRUCT
                        CASE WHEN ee.df_step = TRUE THEN 'test_df' ELSE NULL END AS df_step,
                        ee.df_status AS df_status,
                        SAFE_CAST (NULL AS STRING) AS team,
                        UNION ALL SELECT AS STRUCT
                        CASE WHEN ee.ir_step = TRUE THEN 'test_ir' ELSE NULL END AS ir_step,
                        ee.ir_status AS ir_status,
                        SAFE_CAST (NULL AS STRING) AS team2,
                        verification_sent) AS info,
     COALESCE (ee.email, ee.engagement_email) AS email,
     ee.synced_at
FROM `project_id.dataset.table_name_a` ee
LEFT JOIN `project_id.dataset.table_name_b` cf
     ON cf.b_id = ee.a_id
WHERE ee._id <> 'flow333333333'
AND (ee.team_name < > 'temp' OR ee.team_name IS NULL)
```

**Comment by klahnakoski** [comment]
i am looking at this

**Comment by klahnakoski** [comment]
@MagdaSousa  I am still working on this, it is a bit challenging. In the meantime:

Is there supposed to be a CASE keyword here?

![image](https://user-images.githubusercontent.com/2334429/224319013-99b91edc-6a64-457f-a514-d549abe2f62d.png)

Also, I noticed the not-equal operator `<>` has a space.  I already fixed the parser to handle this, but I would like to confirm.  I wonder if all compound operators can have spaces.

**Comment by MagdaSousa** [comment]
@klahnakoski 
About the different operator <> having a space, it was my mistake when copying the query, I will adjust, it is not expected to have spaces

**Comment by MagdaSousa** [comment]
@klahnakoski , about the CASE keyword, yes it should have, I'll adjust it, I must have deleted it during query formatting

adjusted:
![image](https://user-images.githubusercontent.com/55951781/224380481-ea9a6509-7694-464c-a1f0-727f960f0c1d.png)

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/38c53dcf090a94b388ee85d5de609892f5c3f56d#diff-028acb5a76624487a6dfd257ba58d641b4a84b95750894e2d5e0e9005032c7f3R1234

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.357.23070/
