### ISSUE TITLE
Adding Merge statements as supported query

### ISSUE THREAD

**Issue by stebranchi** [klahnakoski/mo-sql-parsing#167]
Cannot find online a parser that can handle MERGE statements. I think it could be a great improvement for your project. Here an example of statement:

MERGE INTO TMP_TABLE1 TMP1
USING TMP_TABLE1 TMP2
ON TMP1.col1 =TMP2.col1
AND TMP1.col2=TMP2.col2
AND TMP1.col3=TMP2.col3
AND (TMP2.col4 - 1) = TMP1.col4
WHEN MATCHED THEN
UPDATE SET ZTAGG_END = TMP2.ZTAGG

**Comment by klahnakoski** [comment]
I agree.  this looks like a good addition!

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/9407676c922eff59639ffe6580ab6d86a4729ca8

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.366.23085/
