### ISSUE TITLE
WHERE without FROM is not understood

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#174]
Hi,

after long time, we found another one :slightly_smiling_face: 

```sql
SELECT
  1
WHERE
  TRUE
```

raises `ParserError: Expecting {StringEnd} | {except} | {from} | {order} | {offset} | {fetch} | {limit} | {for}, found "WHERE\n    "`

I know this query looks a bit esoteric, but it is valid and returns the expected result (`SELECT 1`) in at least **Athena (PrestoDB)** and **Postgres**. I think that a parser should work on valid SQL no matter how esoteric it is :joy: 

Our simplified real life example is:

```sql
SELECT
  'error'
WHERE
  NOT EXISTS (SELECT 1 FROM other_cte)
```

Thanks in advance!

**Comment by klahnakoski** [comment]
Thank you for providing a succinct test!

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/4cada545e622230fbf2cc5e45d777908d0383e23

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.376.23121/

**Comment by sbrandtb** [comment]
Thanks for fixing, super fast and reliable, as always :slightly_smiling_face:
