### ISSUE TITLE
Some fields in EXTRACT on PrestoDB/Athena not understood

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#175]
After fixing #174, we discovered another issue:

```sql
SELECT EXTRACT(DOW FROM col)
```

Returns 6 in both *Athena (PrestoDB)* and *Postgres*. I was surprised that such a standard SQL function raises ParserError. After investigation with testing all fields from [PrestoDB's documentation](https://prestodb.io/docs/current/functions/datetime.html#extraction-function), I found out that following fields do not work and raise `ParserError` (indepentent of lower/upper casing):

* DAY_OF_MONTH
* DAY_OF_WEEK
* DAY_OF_YEAR
* DOW
* DOY
* YEAR_OF_WEEK
* YOW

Further, I checked [Postgres 15's docs](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT) and found out that following fields are not working:

* decade
* dow ("lucky" overlap with PrestoDB :slightly_smiling_face: )
* doy
* millennium

The raised error is in every case:

```
Expecting {filter} | {order} | {limit} | {filter} | {order} | {limit}, found "from col)"
```

Thanks again!

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/fedf5133ef190b1251628b21ff3f4009a8403d2a

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.377.23123/
