### ISSUE TITLE
Case statement: Example of mismatched conditions  

### ISSUE THREAD

**Issue by davis383** [klahnakoski/mo-sql-parsing#176]
Query example: 

SELECT OrderID, Quantity,
CASE
    WHEN Quantity > 30 THEN 'The quantity is greater than 30'
    WHEN Quantity = 30 THEN 'The quantity is 30'
    ELSE 'The quantity is under 30'
END
FROM OrderDetails;

Parse results: 

{'select': [{'value': 'OrderID'}, {'value': 'Quantity'}, {'value': {'case': [{'then': {'literal': 'The quantity is greater than 30'}, 'when': {'gt': ['Quantity', 30]}}, {'then': {'literal': 'The quantity is 30'}, 'when': {'eq': ['Quantity', 30]}}, {'literal': 'The quantity is under 30'}]}}], 'from': 'OrderDetails'}

'when' conditions are misaligned and 'else' is not handled. 

Thanks for this great parser! Plan to use it a lot, so want to help improve it. However, I do not think my python skills are up to changing the code unfortunately.

**Comment by klahnakoski** [comment]
The parse is correct.  Looking at just the case statement, we have

                {"value": {"case": [
                    {"then": {"literal": "The quantity is greater than 30"}, "when": {"gt": ["Quantity", 30]}},
                    {"then": {"literal": "The quantity is 30"}, "when": {"eq": ["Quantity", 30]}},
                    {"literal": "The quantity is under 30"},
                ]}}

the `case` operator accepts a list of `when`/`then` expressions, plus one (optional) default expression at the end, which is intended to be the `else` clause.
