### ISSUE TITLE
Select FROM Values parsed and  formatted  incorrectly 

### ISSUE THREAD

**Issue by rostykob** [klahnakoski/mo-sql-parsing#177]
Hello,

Found an issue. 
query like 
```
SELECT value1, value2 FROM (VALUES ('A', 'B'), ('C', 'D'), ('E', 'D')) table (value1, value2)
```
Parsed and formatted incorrectly.
Parsed dict looks like this : `{'select': [{'value': 'value1'}, {'value': 'value2'}], 'from': {'value': {}, 'name': {'table': ['value1', 'value2']}}}`, where we can see that values are missing (should be something similar like in insert. When query is formatted back,
it looks like `SELECT value1, value2 FROM  AS TABLE(value1, value2)`. Besides missing values, `table` became uppercase

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/d236ce158fc048f944d485f22098cd4176af8c65

**Comment by klahnakoski** [comment]
wow!  that broke everything...

**Comment by klahnakoski** [comment]
fixed:  https://github.com/klahnakoski/mo-sql-parsing/commit/9bbf8da7ca96eddc7ce07cc23609f01dc336cda0

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.386.23135/

**Comment by rostykob** [comment]
Many thanks Kyle !
