### ISSUE TITLE
SQL query is not parsed, when  one of parameters is subquery

### ISSUE THREAD

**Issue by rostykob** [klahnakoski/mo-sql-parsing#180]
Hello, 

Query 
`SELECT concat( ( SELECT value FROM schema.table a where b = c ), RIGHT( '00' + CAST(MONTH(d) AS VARCHAR(2)), 2 ) ) AS res` 
will not be parsed exception:
`ParseException: Expecting {order} | {offset} | {fetch} | {limit} | {for} | {limit} | {order} | {offset} | {fetch} | {limit} | {for} | {limit}, found ", RIGHT( '" (at char 72), (line:1, col:73)`
 If I move subquery to be last parameter, or be only one parameter, it works

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/c4b224d02ec38edbdbcca22cf7afe6b1dc0ecd49

**Comment by klahnakoski** [comment]
Thank you very much for submitting this bug.  Sorry it took so long to fix:

https://pypi.org/project/mo-sql-parsing/
