### ISSUE TITLE
Formatting: using distinct does not add needed parentheses 

### ISSUE THREAD

**Issue by miahi** [klahnakoski/mo-sql-parsing#181]
Formatting (MSSQL) queries using `distinct` does not add the parentheses from the subqueries in that same query:

`select (SELECT GETDATE() as dd) as currentdate`
is parsed as 
`{'select': {'value': {'select': {'value': {'getdate': {}}, 'name': 'dd'}}, 'name': 'currentdate'}}`
and formatted again as 
`SELECT (SELECT GETDATE() AS dd) AS currentdate`
and that is correct. 

But adding `distinct` in that same query (that is valid):
`select distinct (SELECT GETDATE() as dd) as currentdate`
will parse it correctly:
`{'select_distinct': {'value': {'select': {'value': {'getdate': {}}, 'name': 'dd'}}, 'name': 'currentdate'}}`
but formatting does not add the parentheses as before:
`SELECT DISTINCT SELECT GETDATE() AS dd AS currentdate`
and this query will not parse in MSSQL

Full sample:
```
import mo_sql_parsing

works = "select (SELECT GETDATE() as dd) as currentdate"
doesnt = "select distinct (SELECT GETDATE() as dd) as currentdate"

print(works)
print(mo_sql_parsing.parse_sqlserver(works))
print(mo_sql_parsing.format(mo_sql_parsing.parse_sqlserver(works)))
print(doesnt)
print(mo_sql_parsing.parse_sqlserver(doesnt))
print(mo_sql_parsing.format(mo_sql_parsing.parse_sqlserver(doesnt)))```

**Comment by klahnakoski** [comment]
thank you for submitting this bug report!

https://github.com/klahnakoski/mo-sql-parsing/commit/5875f42de0bba532d7d0b73483e62e95fe5f9d2f

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.408.23161/

**Comment by miahi** [comment]
Thank you for the quick fix!
