### ISSUE TITLE
Doesn't recognize alias in PIVOT operator

### ISSUE THREAD

**Issue by MagdaSousa** [klahnakoski/mo-sql-parsing#182]
Hi!
We find this error when running a query like the below in BQ.
mo_parsing.exceptions.ParseException: Expecting for, found "as jobs\n  " (at char 356), (line:18, col:13)

sample:

```
SELECT * from (
  SELECT
    rt.projectId,
    rt.datasetId,
    rt.tableId,
    count(distinct rt.jobId) jobs
  FROM
    ´`project.dataset.table_test`´ rt
  Group by 1,2,3,4

) PIVOT (
  sum(jobs) as jobs
  for statementType in (
    'BEGIN_TRANSACTION'
    , 'SCRIPT'
    , 'MERGE'
    , 'CREATE_TABLE_AS_SELECT'
    , 'UPDATE'
    , 'SELECT'
    , 'TRUNCATE_TABLE'
    , 'DELETE'
    , 'CREATE_VIEW'
    , 'DROP_VIEW'
    , 'DROP_TABLE'
    , 'COMMIT_TRANSACTION'
    , 'INSERT'
    , 'CREATE_TABLE_FUNCTION'
    , 'ASSERT'
    , 'CREATE_FUNCTION'
    , 'QUERY_STATEMENT_TYPE_UNSPECIFIED'
    , 'ALTER_TABLE'
    , 'CREATE_TABLE'
  )
)
```

**Comment by klahnakoski** [comment]
looking now.  it seems the `\u00b4` around the table name is the culprit

**Comment by klahnakoski** [comment]
I removed the `\u00b4` surrounding the table name. I assume it was a cut-and-paste error.  Then fixed the parse problem you reported.

https://github.com/klahnakoski/mo-sql-parsing/commit/e08bf79e8060273c38d4236d6c37a250ae06f396

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.410.23165/
