### ISSUE TITLE
question about getting original table and column names

### ISSUE THREAD

**Issue by Oest1980** [klahnakoski/mo-sql-parsing#184]
I have a use case, where I need to get the original table and column names as they can be aliased: I'm currently writing a parser for the data structure this repo is producing, but this is a bigger(?) task: Do you know of any way of getting the original table and column names from a sql statement?

**Comment by klahnakoski** [comment]
I occasionally get this type of request.  You are correct, it is a "bigger" task.  You may consider using https://github.com/klahnakoski/mo-sql-parsing/pull/26, which may still work and provide you with what you are looking for.

**Comment by ninja96826** [comment]
hi @klahnakoski is there any documentation of this library ?

**Comment by klahnakoski** [comment]
@ninja96826   sorry, no docs.
