### ISSUE TITLE
does not  recognise update,separator and undefined view 

### ISSUE THREAD

**Issue by ninja96826** [klahnakoski/mo-sql-parsing#185]
error - mo_parsing.exceptions.ParseException: Expecting {column_options} | {window_clause} | {or}, found "ON UPDATE "

**Comment by klahnakoski** [comment]
@ninja96826 sorry for the late reply.  Do you happen to have a sample of the SQL that caused this problem?

**Comment by Rohit44647** [comment]
sql -- substring_index(group_concat(`manager`.`id` order by `manager`.`create` DESC separator ','), ',', 1) AS `s_id`
error -- mo_parsing.exceptions.ParseException: Expecting {nulls} | {limit} | {nulls} | {limit} | {nulls} | {limit} | {nulls} | {limit}, found "separator " (at char 184), (line:6, col:92)

sql -- `lastcreated` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
error -- mo_parsing.exceptions.ParseException: Expecting {column_options} | {window_clause} | {or}, found "ON UPDATE " (at char 224), (line:6, col:52)


sql -- CREATE OR REPLACE
ALGORITHM = UNDEFINED VIEW  `view_name` AS                                                                                            
error --  mo_parsing.exceptions.ParseException: Expecting {transient} | {table} | {transient} | {view}, found "ALGORITHM " (at char 19), (line:3, col:1)

**Comment by ninja96826** [comment]
sql -- substring_index(group_concat(manager.id order by manager.create DESC separator ','), ',', 1) AS s_id
error -- mo_parsing.exceptions.ParseException: Expecting {nulls} | {limit} | {nulls} | {limit} | {nulls} | {limit} | {nulls} | {limit}, found "separator " (at char 184), (line:6, col:92)

sql -- lastcreated datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
error -- mo_parsing.exceptions.ParseException: Expecting {column_options} | {window_clause} | {or}, found "ON UPDATE " (at char 224), (line:6, col:52)

sql -- CREATE OR REPLACE
ALGORITHM = UNDEFINED VIEW view_name AS
error -- mo_parsing.exceptions.ParseException: Expecting {transient} | {table} | {transient} | {view}, found "ALGORITHM " (at char 19), (line:3, col:1)

**Comment by klahnakoski** [comment]
working on solutions...

https://github.com/klahnakoski/mo-sql-parsing/commit/86b9c877774535e418d44772680c7e283bb56344

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/afd3b24fb91736efba302aa5aa89507e43c4be64
https://github.com/klahnakoski/mo-sql-parsing/commit/378cee4fb49f0cc46c4a404898756be8033012ac

**Comment by klahnakoski** [comment]
@ninja96826 Thank you for the submissions!  

https://pypi.org/project/mo-sql-parsing/9.424.23203/

**Comment by ninja96826** [comment]
thank you @klahnakoski for quick response

**Comment by ninja96826** [comment]
i found one issue it was not able to parse this                                            
code = from mo_sql_parsing import parse, normal_op

sql = """
CREATE TABLE IF NOT EXISTS `industry_i18n` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `company_name` varchar(765)  DEFAULT NULL,
  `locale` varchar(765)  DEFAULT NULL,
  `master_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_master_i18n` (`master_id`),
  KEY `rm_id` (`master_id`),
  KEY `locale_id` (`master_id`,`locale`(255))
) ;

"""

ast = parse(sql, calls=normal_op)
print(ast)

error = mo_parsing/core.py", line 171, in _parseString
    raise cause.best_cause from None
mo_parsing.exceptions.ParseException: Expecting {.} | {,} | {)}, found "(255))\n) " (at char 340), (line:10, col:40)

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/0e9454165e7c76fee573c8432762f70376852fa3

**Comment by klahnakoski** [comment]
Thanks again!

https://pypi.org/project/mo-sql-parsing/9.427.23208/
