### ISSUE TITLE
the limit 0,10 triggers a bug

### ISSUE THREAD

**Issue by hcymysql** [klahnakoski/mo-sql-parsing#186]
```
from mo_sql_parsing import parse

sql_query = "SELECT * from t1 limit 1,10"

parsed_query = parse(sql_query)

print(parsed_query)
```
---------------------------------------------------------------------------------
result:
```
    raise cause.best_cause from None
mo_parsing.exceptions.ParseException: Expecting {StringEnd} | {offset} | {fetch} | {for}, found ",10" (at char 24), (line:1, col:25)
```

**Comment by klahnakoski** [comment]
thank you very much for this submission!

https://github.com/klahnakoski/mo-sql-parsing/commit/a95c6307758a0a8aaa5e70856fe65591711f923a

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.423.23199/
