### ISSUE TITLE
T-sql "SELECT TOP X [column1] ..." Fails 

### ISSUE THREAD

**Issue by JacksonnF** [klahnakoski/mo-sql-parsing#189]
The SELECT TOP X functionality fails if square brackets are used to delimitate individual columns.

The following code fails 
``` 
from mo_sql_parsing import parse_sqlserver
parsed = parse_sqlserver('SELECT TOP 10 [Column] FROM A ORDER BY [relevance]')
```
```
ParseException: Expecting {percent} | {filter} | {with} | {expression}, found "FROM A ORD" (at char 23), (line:1, col:24)
```
SELECT TOP X does work for SELECT * statements or if square brackets ([]) are not used to delimitate the columns.

i.e.
Code:
```
parsed = parse_sqlserver('SELECT TOP 10 Column FROM A ORDER BY [relevance]')
```
Output:
```
{'top': 10,
 'select': {'value': 'Column'},
 'from': 'A',
 'orderby': {'value': 'relevance'}}
```
It also works if PERCENT is included in the query
Code:
```
parsed = parse_sqlserver('SELECT TOP 10 PERCENT [Column] FROM A ORDER BY [relevance]')
```
Output: 
```
{'top': {'percent': 10},
 'select': {'value': 'Column'},
 'from': 'A',
 'orderby': {'value': 'relevance'}}
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/d10b37ee3ac8163a65ee7f73c880e3245ddc1600

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.428.23214/

thank you very much for your bug report!
