### ISSUE TITLE
use case

### ISSUE THREAD

**Issue by ninja96826** [klahnakoski/mo-sql-parsing#195]
**_query_** - **CREATE OR REPLACE
VIEW data_view AS
select
u.id AS client_id,
substring_index(group_concat(u.co_id order by u.created DESC separator ','), ',', 1) AS s_id
from
user u
where
(u.event_status in (1, 3))**

**_json_** = **{'create view': {'replace': True,
'name': 'data_view',
'query': {'select': [{'value': 'u.id', 'name': 'client_id'},
{'value': {'substring_index': [{'orderby': {'value': 'u.created',
'sort': 'desc'},
'separator': {'literal': ','},
'group_concat': 'u.co_id'},
{'literal': ','},
1]},
'name': 's_id'}],
'from': {'value': 'user', 'name': 'u'},
'where': {'in': ['u.event_status', [1, 3]]}}}}**

Hi @klahnakoski im having use case where i dont want further parsing of conditions i want the parsing at just 1st level like for value in select for alias or name **s_id** i want just this **"substring_index(group_concat(u.co_id order by u.created DESC separator ','), ',', 1)"** same goes for join conditions as well.

**Comment by klahnakoski** [comment]
@ninja96826  I am not quite sure what you mean, but maybe this will help:

    parse(sql, calls=normal_op)

which provides an easier-to-process "normal form" (used inside the parser itself).  This form will ensure every function call has `op`, `args` and `kwargs` (like Python`).

Example:

```
{
    "op": "group_concat",
    "args": ["u.co_id"],
    "kwargs": {
        "orderby": {"value": "u.created", "sort": "desc"},
        "separator": {"literal": ","},
    },
}
```

here is the whole query:


```
{"create view": {
    "replace": True,
    "name": "data_view",
    "query": {
        "select": [
            {"value": "u.id", "name": "client_id"},
            {
                "value": {
                    "op": "substring_index",
                    "args": [
                        {
                            "op": "group_concat",
                            "args": ["u.co_id"],
                            "kwargs": {
                                "orderby": {"value": "u.created", "sort": "desc"},
                                "separator": {"literal": ","},
                            },
                        },
                        {"literal": ","},
                        1,
                    ],
                },
                "name": "s_id",
            },
        ],
        "from": {"value": "user", "name": "u"},
        "where": {"op": "in", "args": ["u.event_status", [1, 3]]},
    },
}}
```

**Comment by ninja96826** [comment]
thankyou @klahnakoski for the prompt reply. In my code, I'm using **(sql, calls=normal_op)** as well . My goal is to create a JSON object that resembles the following structure.If there is any method that can be tweaked to get this result then let me know please.

json

**{
    "create view": {
        "replace": true,
        "name": "data_view",
        "query": {
            "select": [
                {"value": "u.id", "name": "client_id"},
                {
                    "value": "substring_index(group_concat(u.co_id order by u.created DESC separator ','), ',', 1)",
                    "name": "s_id"
                }
            ],
            "from": {"value": "user", "name": "u"},
            "where": {"(u.event_status in (1, 3))"}
        }
    }
}**

**Comment by klahnakoski** [comment]
You can try formatting the parts you want as a string: 

```
result = parse(sql)

selects = result["create view"]["query"]["select"]
for select in selects:
    if "value" in select:
        select["value"] = format(select["value"])
```

But the formatter is not as mature as the parser.  I added a test for your example,
https://github.com/klahnakoski/mo-sql-parsing/commit/a7fc33530aa86228112b69f648336eb395ecddd2#diff-77e357ea1ebd625dbc52532a43f82e67a856e499d3d0b1427b57a71c6f85056aR780

I am working releasing that change now...



FYI: you can see me trying that here:

https://github.com/klahnakoski/mo-sql-parsing/commit/1f5c49692cd3974be3e6fb49ab9e5a2a76862f14#diff-b6b46dcb2319fb801981b07a7dd50bcd9393dd824c31822a484b1113a396d472L508

**Comment by klahnakoski** [comment]
try the technique with this:

https://pypi.org/project/mo-sql-parsing/9.430.23234/

please open issues when you find problems formatting 😄
