### ISSUE TITLE
Exception when parsing BigQuery cast with format 

### ISSUE THREAD

**Issue by fireis** [klahnakoski/mo-sql-parsing#205]
Hello! We are using mo_sql_parsing to parse some queries from our clients, and we have realized that the parser is failing when parsing the followingBigQuery statement:

`select CAST(date(2023,1,1) AS STRING FORMAT 'YYYY-MM') AS year_month`

It throws the exception: `Expecting {RB} | {character} | {as} | {RB} | {character} | {as}, found "FORMAT 'YY" (at char 37), (line:1, col:38)`.

Does it make sense for the parser to support this casting type with format?

**Comment by klahnakoski** [comment]
@fireis sorry for the delay.  Let me review these today.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/8fd7f27b8b688114878214c83606357ef8993a1c

**Comment by klahnakoski** [comment]
@fireis   thank you very much for these issues.  the version with those fixes are here:

https://pypi.org/project/mo-sql-parsing/9.460.23319/
