### ISSUE TITLE
Exception when parsing BigQuery query with 'except'

### ISSUE THREAD

**Issue by fireis** [klahnakoski/mo-sql-parsing#206]
Hello, we are using mo_sql_parsing to parse some queries, and we have realized that the parser is failing when parsing a BigQuery statement that contains except and explicit column selection. 

The following snippet exemplifies the issue we are facing:

```
import mo_sql_parsing

query = """
with raw_data as (
   select 
          * 
   from UNNEST(GENERATE_ARRAY(1, 2)) as col1,
   UNNEST(GENERATE_ARRAY(10, 12)) as col2,
   UNNEST(GENERATE_ARRAY(20, 22)) as col3
)
select 
    * except(col3), 
    col3 + col1 as new_col
from raw_data
"""

mo_sql_parsing.parse(query)
```
This snippet returns: `ParseException: Expecting {StringEnd} | {from} | {where} | {group} | {having} | {window} | {qualify} | {order} | {for}, found "col3 + col" (at char 210), (line:11, col:5)`

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/8a3b4de39029938cfac1e4a6c31d3e2099b43378

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.460.23319/
