### ISSUE TITLE
Exception when parsing BigQuery statement that renames the result of the struct function

### ISSUE THREAD

**Issue by fireis** [klahnakoski/mo-sql-parsing#207]
Hello, we are using mo_sql_parsing to parse some queries, and we have realized that the parser is failing when parsing a valid BigQuery statement that renames the result of a 'struct' function. The following snippet exemplifies the issue with a simple, valid query we are facing:
```
import mo_sql_parsing

query = """select struct('a' as col1) as cc"""

mo_sql_parsing.parse(query)

```
The exception is as follows: `ParseException: Expecting {RB} | {order} | {limit} | {separator} | {RB} | {order} | {limit} | {separator}, found "as col1) a" (at char 18), (line:1, col:19)`

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/6fc83aea848e5840b809b3e625fdbc0576bd4a72

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.460.23319/
