### ISSUE TITLE
Exception when parsing BigQuery statement with unnest on 'from'

### ISSUE THREAD

**Issue by fireis** [klahnakoski/mo-sql-parsing#216]
We found an exception when parsing BigQuery queries that used unnest inside the 'from' statement. The following snippet exemplifies the issue we are facing:

```
import mo_sql_parsing

query = """
            with raw_data as (
            select 
                    * 
            from UNNEST(GENERATE_ARRAY(1, 2)) as col1
            ),
            raw_data2 as (
            select 
            *, 
            1 as cn1, 
            2 as cn2, 
            from UNNEST(GENERATE_ARRAY(1, 2)) as col2
            )
            select 
                *
            from raw_data
            left join raw_data2 on raw_data.col1 = raw_data2.col2, unnest ([raw_data2.cn1, raw_data2.cn2]) as unnested_res
"""
parsed_sql = mo_sql_parsing.parse(query)
print(parsed_sql)
```

As it returns the exception `mo_parsing.exceptions.ParseException: Expecting {LB} | {join} | {StringEnd} | {where} | {group} | {having} | {window} | {qualify} | {order} | {for}, found ", unnest (" (at char 450), (line:17, col:66)` even though the query is valid and returns the following result on BigQuery:
```
col1	col2	cn1	cn2	unnested_res
1	1	1	2	1
1	1	1	2	2
2	2	1	2	1
2	2	1	2	2
```

**Comment by klahnakoski** [comment]
will get parsed as:

```
{
    "select": [{"value": {"add": ["col3", "col1"]}, "name": "new_col"}, {"all_columns": {}, "except": "col3"}],
    "from": "raw_data",
    "with": {
        "name": "raw_data",
        "value": {
            "select": "*",
            "from": [
                {"value": {"unnest": {"generate_array": [1, 2]}}, "name": "col1"},
                {"value": {"unnest": {"generate_array": [10, 12]}}, "name": "col2"},
                {"value": {"unnest": {"generate_array": [20, 22]}}, "name": "col3"},
            ],
        },
    },
}
```

which shows an irregularity:  Parsing `*` and `* except x` results in very different json.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/51c420729cb2031b9a6f86ba36a095029136d953

**Comment by klahnakoski** [comment]
this feature is in both 9 and 10

https://pypi.org/project/mo-sql-parsing/9.469.23343/
https://pypi.org/project/mo-sql-parsing/10.469.23343/
