### ISSUE TITLE
SET, ENUM and more support

### ISSUE THREAD

**Issue by Harveyhase68** [klahnakoski/mo-sql-parsing#218]
Hello,

thank you for your wonderful work, I was looking long time for such a good library!

I stumbled upon a few things: (which will make it really better!)

Is it possible, you can only parse 1 query, if a second query added after the first, we got always:

mo_parsing.exceptions.ParseException: Expecting {StringEnd} | {as} | {cluster}, found ";\nCREATE T" (at char 1148), (lin
e:25, col:57)

maybe you have a look at the official sakila.sql from Oracle MySQL? I attached it for you.

[sakila-schema.zip](https://github.com/klahnakoski/mo-sql-parsing/files/13708392/sakila-schema.zip)

For data-types, the only really major thing which **I need to have added** will be:
**SET, ENUM data types from mysql, break the recognition and stop execution**

Some issues I got from **CREATE VIEW** too:

CREATE VIEW "customer_list"
AS
SELECT cu.customer_id AS ID, CONCAT(cu.first_name, _utf8mb4' ', cu.last_name) AS name, a.address AS address, a.postal_code AS `zip code`,
	a.phone AS phone, city.city AS city, country.country AS country, IF(cu.active, _utf8mb4'active',_utf8mb4'') AS notes, cu.store_id AS SID
FROM customer AS cu JOIN address AS a ON cu.address_id = a.address_id JOIN city ON a.city_id = city.city_id
	JOIN country ON city.country_id = country.country_id;

Everything else is for completeness, which I can filter out, before execution, so not really necessary:

**START TRANSACTION, COMMIT** not recognized and should be ignored, break the execution

error on **SET**:
**SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";**

**DROP TABLE IF EXISTS** `product`; breaks the rules

**INSERT INTO** `product`, should be ignored

Multiline comments does not work (should be ignored):
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;

Here is my test script, which is a 1:1 export from phpMyAdmin, test database was a MySQL 8.0.33 on Wampserver/Windows 10, maybe a later one, will have more/less issues?

[mysql-product-export-phpmyadmin-short-binary.zip](https://github.com/klahnakoski/mo-sql-parsing/files/13707838/mysql-product-export-phpmyadmin-short-binary.zip)

**Comment by klahnakoski** [comment]
@Harveyhase68 

Thank you for your kind words.  

This library does not have support for user defined functions.   Since you have some specific examples, let me see how much work this is.  I will proceed on the [udf branch](https://github.com/klahnakoski/mo-sql-parsing/tree/udf|).

No promises.

**Comment by klahnakoski** [comment]
It was an exciting evening.  Having the parser change behaviour upon `DELIMITER` is the most interesting.  I am done for today.

https://github.com/klahnakoski/mo-sql-parsing/pull/219/files

**Comment by klahnakoski** [comment]
@Harveyhase68 I added support to handle the examples you gave me.  The latest version has those improvements:

https://pypi.org/project/mo-sql-parsing/10.472.23361/

This new functionality is likely incomplete; expect further parsing problems.  I will appreciate if you submit more issues on this improved parser.    

Thank you for your detailed submission.
