### ISSUE TITLE
MySQL quoting is unusual and doesn't parse correctly

### ISSUE THREAD

**Issue by rogerjane** [klahnakoski/mo-sql-parsing#22]
I believe in ANSI a single quote surrounds strings while double quote is used to 'un-keyword' a token.  However, in MySQL a backquote is used to 'un-keyword' while single and double quote both mean literal strings.  Is there a way to parse using the MySQL meaning so that the following:

SELECT 'fred'
SELECT "fred"

Both give:

{"select": {"value": {"literal": "fred"}}}

Currently the latter is interpreted as SELECT fred and hence results in:

{"select": {"value": "fred"}}

**Comment by klahnakoski** [comment]
this is my failed attempt:  https://github.com/klahnakoski/mo-sql-parsing/commit/1b0d7a9324347e4b7cc257ad0d4bad5ea17ee2aa

the problem is the optimized parser does not see the change in `literal_string`.

**Comment by klahnakoski** [comment]
fixed here: https://github.com/klahnakoski/mo-sql-parsing/commit/a0fe98df2f671b2b345704a0f3f20c4a86166814

it was easier to put the parser specification into a function, and call that function with literal/ident parameters.  This has the added benefit of not generating a parser at import time, rather at time of first call.
