### ISSUE TITLE
Parsing error when using window function

### ISSUE THREAD

**Issue by fireis** [klahnakoski/mo-sql-parsing#222]
While parsing a query that references a window statement, we have found the following exception `Expecting {RB} | {partition} | {order} | {RB} | {partition} | {order} | {RB} | {partition} | {order} | {RB} | {partition} | {order}, found "item_windo" (at char 150), (line:6, col:22)`. 
The following query helps to reproduce this issue:
```SQL
WITH Produce AS (
  SELECT 'Kale' as product, 51 as Q1 UNION ALL
  SELECT 'Kale' as product, 10 UNION ALL
  SELECT 'Apple', 77)
SELECT sum(Q1) OVER (item_window) AS sum_Q1
FROM Produce
WINDOW item_window AS (
  PARTITION BY product
  )
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/1d8d62edf2fc9899f17b8105f3975c31c329777a

**Comment by klahnakoski** [comment]
Thank you very much for this submission. both version 9 and 10 have this fix.  here is version10

https://pypi.org/project/mo-sql-parsing/10.471.23361/
