### ISSUE TITLE
Error parsing BigQuery table name with dash and without `

### ISSUE THREAD

**Issue by fireis** [klahnakoski/mo-sql-parsing#227]
We discovered that the parsing fails when we use a fully-qualified table name such as `proj-prd.dataset.table` without using the enclosing `.

So, for example:

```Python
query = """ select * from `proj-prd.dataset.table`"""
parsed_sql = mo_sql_parsing.parse(query)

```

The following fails, even though it can be executed by BigQuery:

```Python
query = """ select * from proj-prd.dataset.table"""
parsed_sql = mo_sql_parsing.parse(query)

```
> mo_parsing.exceptions.ParseException: Expecting {LB} | {with} | {tablesample} | {join} | {StringEnd} | {with} | {for} | {where} | {group} | {having} | {window} | {qualify} | {order} | {for}, found "-prd.datas" (at char 19), (line:1, col:20)

Do you think this support is something that makes sense to be implemented?

**Comment by klahnakoski** [comment]
Thank you for submitting this!  Here is the fix:

https://pypi.org/project/mo-sql-parsing/10.499.24023/

**Comment by klahnakoski** [comment]
Did this get reverted?

https://github.com/klahnakoski/mo-sql-parsing/commit/78b8a851554dd8534d5ccddeb50dfb2f014e00f3

https://pypi.org/project/mo-sql-parsing/10.627.24135/
