### ISSUE TITLE
Sql using the Redshift "right" function leads to a Parsing Exception

### ISSUE THREAD

**Issue by aaronbrown1988** [klahnakoski/mo-sql-parsing#23]
Minimal SQL to reproduce:
`SELECT RIGHT(a,6)  FROM b`

Example usage of the function can be found here: https://docs.aws.amazon.com/redshift/latest/dg/r_LEFT.html

The exception:
`mo_parsing.exceptions.ParseException: Expecting *, found "RIGHT(a,6)" (at char 7, (line:1, col:8)`

**Comment by aaronbrown1988** [comment]
I have a fix here: https://github.com/aaronbrown1988/mo-sql-parsing/tree/fix-issue-23 

Would you prefer I create a PR from for this to master/main or  dev ? I'm happy to do either.

**Comment by klahnakoski** [comment]
added test https://github.com/klahnakoski/mo-sql-parsing/commit/9a79458eb01a3f88b76093e13f44bd2c90f0f35a
fixed problems https://github.com/klahnakoski/mo-sql-parsing/commit/fb210a8b296221e3c8b14df53aa7d0970416b84b
