### ISSUE TITLE
Can not recognize IS NULL or IS NOT NULL

### ISSUE THREAD

**Issue by MrRRcc** [klahnakoski/mo-sql-parsing#230]
sql = 'select id from tbl where id is null'
when i parse sql, i get where value is {'missing':'id'}

**Comment by klahnakoski** [comment]
Yes, that is deliberate.  Although, I do see the benefit of calling it `is_null`

**Comment by klahnakoski** [comment]
Let me see if I can make it an option.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/896aec4c72b5693bc0b2090a25d8900705a38bff

**Comment by klahnakoski** [comment]
use the new `fmap` parameter to give the 'missing' function a better name:

```
C:\Users\kyle\code\jx-sqlite>c:\Python310\python.exe
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>from mo_sql_parsing import parse
>>> parse("select id from tbl where id is null", fmap={"missing":"is_null", "exists":"is_not_null"})
>>> {'select': {'value': 'id'}, 'from': 'tbl', 'where': {'is_null': 'id'}}
```

https://pypi.org/project/mo-sql-parsing/10.581.24094/
