### ISSUE TITLE
[MSSQL] parsing or a query fails datetimeoffset

### ISSUE THREAD

**Issue by rostykob** [klahnakoski/mo-sql-parsing#231]
Hello, below query failed to be parsed in mssql. I use mo_sql_parsing ver 9 ( but I would gess it will be same for 10)

`select count(*) as r_c, SUM(CASE WHEN NOT (t_dt = CAST(FORMAT(t_dt, 'yyyy-MM-ddTHH:mm:ss.ffffff') AS datetimeoffset)) THEN 1 ELSE 0 END) as e_c from [dbo].[table]
`

It gives and error `Expecting column_type, found "datetimeof`

**Comment by klahnakoski** [comment]
Thank you for this submission!  

https://github.com/klahnakoski/mo-sql-parsing/commit/59d9952e81a29a1cd0f679b1bdfa0225f34f8c6d

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/10.581.24094/
