### ISSUE TITLE
UNION ALL is lost after format

### ISSUE THREAD

**Issue by twoonefour8** [klahnakoski/mo-sql-parsing#233]
Hi!

Thank you for the previous help!

Now I have another problem..

I have SQL like this:
```sql
WITH table_test AS (
  SELECT public.categories.string_agg AS string_agg
  FROM public.categories
)
SELECT * FROM table_test
UNION ALL
SELECT * FROM table_test
```

`parse()` return JSON:
```json
{
  "union_all": [
    {
      "select": {
        "all_columns": {}
      },
      "from": "table_test"
    },
    {
      "select": {
        "all_columns": {}
      },
      "from": "table_test"
    }
  ],
  "with": {
    "name": "table_test",
      "value": {
        "select": {
          "name": "string_agg",
          "value": "public.categories.string_agg"
        },
	"from": "public.categories"
    }
  }
}
```

But if I convert it back with `format()` sql lost `UNION ALL` block
```sql
WITH table_test AS (
  SELECT public.categories.string_agg AS string_agg
  FROM public.categories
)
```

**Comment by klahnakoski** [comment]
Sorry for the delay:  https://github.com/klahnakoski/mo-sql-parsing/commit/5e15d41c010a3fdfba5442b3a642d7db9a870108

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/10.627.24135/

**Comment by twoonefour8** [comment]
@klahnakoski Sorry for the long reply. Everything works with `UNION ALL` but does not work with `UNION`

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/11.658.24326/

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/de670c1919e7b4b4811f6d11e52f3c803ed88034

**Comment by twoonefour8** [comment]
@klahnakoski Thank you! It works!
