### ISSUE TITLE
The issue of JSONB parse failure in PostgreSQL

### ISSUE THREAD

**Issue by wozuishuai997** [klahnakoski/mo-sql-parsing#239]
When using postgreSQL, when using the syntax of jsonb ->>'field_key', calling the parse() method will result in an error.
error info:
Expecting table_source, found "> 'a4e842a" (at char 1526), (line:4, col:84)

**Comment by klahnakoski** [comment]
@wozuishuai997   Thank you for mentioning this!  I had not considered any of the jsonb operators:

https://www.postgresql.org/docs/9.5/functions-json.html

**Comment by klahnakoski** [comment]
There is likely more, and there is no formatting for these operators.  Please submit another issue when you find something else.

https://github.com/klahnakoski/mo-sql-parsing/commit/1ff7931bc07d732d1394cfb6fc5e8f8d536cdfeb

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/10.643.24144/
