### ISSUE TITLE
Formatter does not add parenthesis as it should

### ISSUE THREAD

**Issue by dominusmi** [klahnakoski/mo-sql-parsing#244]
Example:
```
parsed = mo_sql_parsing.parse("SELECT * FROM x WHERE (a = $1 AND b = $2) OR (a = $1 AND b = $3)")
result = mo_sql_parsing.format(parsed)

print(result)
> SELECT * FROM x WHERE a = "$1" AND b = "$2" OR a = "$1" AND b = "$3"
```
The parser does work correctly, by wrapping the two AND inside of an OR, but the formatter does not add the parenthesis which completely changes the logic of the query

**Comment by dominusmi** [comment]
Debugged a bit, it has to do with precedence of operators and how it's handled. I'm likely being wrong but these things I thought were strange:
1. The checks are `>=` instead of just `>`. e.g.
```
            if prec > op_prec:
                return method(value, op_prec)
            else:
                return f"({method(value, op_prec)})"
```
Why is that? If two operators have the same precedence, then shouldn't it add parenthesis?

2. Why does `AND` have precedence 10 and `OR` 11? Shouldn't they be the same?
3. Why is the first operator provided with an extra `0.25` precedence?
```
            if i == 0:
                acc.append(self.dispatch(v, op_prec + 0.25))
            else:
                acc.append(self.dispatch(v, op_prec))
```

Aside from all of that, why can't we just always add parenthesis rather than try to do this precedence? Is it because some operators don't handle parenthesis well? Would solve the correctness issue

**Comment by klahnakoski** [comment]
@dominusmi,

Operators with lower precedence are applied first.   `AND` is performed first, then any `OR`.  In the case of

    a = "$1" AND b = "$2" OR a = "$1" AND b = "$3"

it is the same as 

    (a = "$1" AND b = "$2") OR (a = "$1" AND b = "$3")

> The checks are >= instead of just >.

The code

```
            if prec > op_prec:
                return method(value, op_prec)
            else:
                return f"({method(value, op_prec)})"
```

looks correct. `op_prec` is the precedence of the inner operator, which is intended to be done first.  `prec` is the precedence of the outer operator, which is intended to be done second.  We only need parenthesis if the inner is greater-or-equal (done at same time or later) than the outer.

> Why does AND have precedence 10 and OR 11? Shouldn't they be the same?

No.  There is an order-of-operations.  All `AND` are done first, then all `OR`.   But you can change the code so they are the same and see what happens to the formatting.

> Why is the first operator provided with an extra 0.25 precedence?

I have forgotten.  There is probably a test that will break if we remove the 0.25. 

> why can't we just always add parenthesis rather than try to do this precedence?

Without precedence we get a binding number of parenthesis that makes the SQL nearly unreadable.


The precedence code is incomplete.  It may not be ordering all operators correctly, but it certainly is capable of doing so.  We only need to assign the correct values.  Those correct values are dictated by the test cases.  If you can produce a test case that formats with parenthesis placed wrong, then we can improve this code.
