### ISSUE TITLE
left join first

### ISSUE THREAD

**Issue by OmarNour** [klahnakoski/mo-sql-parsing#253]
the below query is not handled: _**(I know this is not a common way to write queries, but sometimes we go like that)**_

```
select t1.col1, t2.col2, t3.col3
from table1 t1
join table2 t2
	left join table3 t3
	on t3.id = t2.id
on t1.id = t2.id
```

error raised:
mo_parsing.exceptions.ParseException: Expecting {lb} | {StringEnd} | {order} | {offset} | {for}, found "on x.id = " (at char 94), (line:6, col:1)

**Comment by klahnakoski** [comment]
Thank you for submitting this!

https://github.com/klahnakoski/mo-sql-parsing/commit/00969de7b2773eac1d12948da0f4c6bdb5a8241e

**Comment by klahnakoski** [comment]
actual fix: https://github.com/klahnakoski/mo-sql-parsing/commit/60233426bdd47e7fc1770cd8c9dd4e31dd269b11#diff-6cc67f4a119445766648230e63d80f11f81c97be4340f5e55a26add729401318

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/10.657.24299/
