### ISSUE TITLE
Wrong parsing and formatting

### ISSUE THREAD

**Issue by adarsh-s-ibm** [klahnakoski/mo-sql-parsing#254]
Here is the sql
`select DATEADD(DAY, SEQ4(), DATEADD('year', -2, last_day(CURRENT_DATE(),'year'))) AS MY_DATE FROM TABLE(GENERATOR(ROWCOUNT=>(366*2)))`

parsed output is,

`{'select': {'name': 'MY_DATE', 'value': {'dateadd': ['DAY', {'seq4': {}}, {'dateadd': [{'literal': 'year'}, -2, {'last_day': [{'current_date': {}}, {'literal': 'year'}]}]}]}}, 'from': {'table': {'ROWCOUNT': {'mul': [366, 2]}, 'genarator': {}}} `

Expected output is,

`{'select': {'name': 'MY_DATE', 'value': {'dateadd': ['DAY', {'seq4': {}}, {'dateadd': [{'literal': 'year'}, -2, {'last_day': [{'current_date': {}}, {'literal': 'year'}]}]}]}}, 'from': {'table': 'genarator': {{'ROWCOUNT': {'mul': [366, 2]}}}}`

**Comment by klahnakoski** [comment]
this is the intended behaviour.  A clearer result can be had using `calls-normal_op` which is more verbose, but is clear about the function name (aka `op`) ans the parameters it has been given.

        result = parse(sql, calls=normal_op)

The format you see munges the function name with the keyword arguments into a single json object.  This is more compact, but requires context to decode (you must know that `generator` is the function name)


    {
        'generator': {},   //function name
        'rowcount': {'mul': [366, 2]}   // keyword argument
    }

**Comment by adarsh-s-ibm** [comment]
But, when we try to do format on this output It is failing to do so, 

format({'select': {'name': 'MY_DATE', 'value': {'dateadd': ['DAY', {'seq4': {}}, {'dateadd': [{'literal': 'year'}, -2, {'last_day': [{'current_date': {}}, {'literal': 'year'}]}]}]}}, 'from': {'table': {'ROWCOUNT': {'mul': [366, 2]}, 'genarator': {}}}) // fails

format({'select': {'name': 'MY_DATE', 'value': {'dateadd': ['DAY', {'seq4': {}}, {'dateadd': [{'literal': 'year'}, -2, {'last_day': [{'current_date': {}}, {'literal': 'year'}]}]}]}}, 'from': {'table': 'genarator': {{'ROWCOUNT': {'mul': [366, 2]}}}}) // works as expected.

**Comment by klahnakoski** [comment]
I added a test using the `normal_op`  to demonstrate

https://github.com/klahnakoski/mo-sql-parsing/commit/60233426bdd47e7fc1770cd8c9dd4e31dd269b11#diff-a82d1c3ecd7beb06662cb47f78ded43cab653a0759ef98153d3b961d149a974cR989

On the subject of formatting:  I have no doubt the formatter is broken, it is often behind the parser.  I can have a look at that too.

**Comment by klahnakoski** [comment]
here is the fix for formatting the generator function.  I really should handle keyword parameters in general.

https://github.com/klahnakoski/mo-sql-parsing/commit/739777db9a33d62ac58c68ee1b2b148fbaaf2529

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/11.656.24305/
