### ISSUE TITLE
Formatter and PIVOT and UNPIVOT

### ISSUE THREAD

**Issue by GilBadel** [klahnakoski/mo-sql-parsing#255]
Hello, thanks for the very useful package !

I noticed that (UN)PIVOT clauses are parsed in a meaningful way by the parser, but are not correctly rendered by the formatter. 
In case of PIVOT, the formatter raises an exception, and in case of unpivot, it ignores the FOR and IN elements and uses the AS as column alias instead of an alias for the unpivoted table.

As examples, see the following toy queries:

### Pivot
 ```import mo_sql_parsing as mosql
query = """SELECT "'val_1'", "'val_2'" FROM tab PIVOT (SUM(col_a) FOR col_b IN ('val_1', 'val_2')) AS p"""
query_json = mosql.parse(query)
output = mosql.format(query_json)
```

query_json :
```{'select': [{'value': "'val_1'"}, {'value': "'val_2'"}],
 'from': ['tab',
  {'pivot': {'aggregate': {'sum': 'col_a'},
    'for': 'col_b',
    'in': {'literal': ['val_1', 'val_2']},
    'name': 'p'}}]}
```
    
output : 
Exception: Operators should have only one key!

### Unpivot
 ```import mo_sql_parsing as mosql
query = "SELECT col_a, col_b FROM tab UNPIVOT (col_a FOR col_b IN (col_1, col_2)) AS u"
query_json = mosql.parse(query)
output = mosql.format(query_json)
```

query_json :
```{'select': [{'value': 'col_a'}, {'value': 'col_b'}],
 'from': ['tab',
  {'unpivot': {'value': 'col_a',
    'for': 'col_b',
    'in': ['col_1', 'col_2'],
    'name': 'u'}}]}
```
    
output : 
`'SELECT col_a, col_b FROM tab, UNPIVOT(col_a AS u)'`

Testted with version 10.656.24252

Many thanks,
Gil

**Comment by klahnakoski** [comment]
Thanks for bringing this up.  The formatter is behind the parser in terms of features.  Let em see what I can do.

**Comment by klahnakoski** [comment]
some fix here:

https://github.com/klahnakoski/mo-sql-parsing/commit/0de939e2ce03a86b05d2e1b29aa9b1ec1ec06fa0

**Comment by klahnakoski** [comment]
Here is the fix: https://pypi.org/project/mo-sql-parsing/11.655.24305/

I increased the major version: https://github.com/klahnakoski/mo-sql-parsing?tab=readme-ov-file#version-11
