### ISSUE TITLE
`WHERE IN` with multiple columns parse → format sequence produce illegal sql

### ISSUE THREAD

**Issue by pohmelie** [klahnakoski/mo-sql-parsing#28]
I used `mo-sql-parsing` from `dev` branch:
``` python
>>> import mo_sql_parsing as sqlp
>>> sqlp.parse("select * from T where (a, b) in (('a', 'b'), ('c', 'd'))")
{'select': '*', 'from': 'T', 'where': {'in': [['a', 'b'], [{'literal': ['a', 'b']}, {'literal': ['c', 'd']}]]}}
>>> sqlp.format(_)
"SELECT * FROM T WHERE ['a', 'b'] IN ('a', 'b'), ('c', 'd')"
```
So, the square brackets after `WHERE` are illegal sql syntax.

**Comment by klahnakoski** [comment]
thank you!  The formatter was never given much love, but tests will force it to be better.

**Comment by klahnakoski** [comment]
added test https://github.com/klahnakoski/mo-sql-parsing/commit/479d444f3897d383b02b40697b2befab2db7f785#diff-77e357ea1ebd625dbc52532a43f82e67a856e499d3d0b1427b57a71c6f85056aR420
