### ISSUE TITLE
Set difference operator causes ParseException

### ISSUE THREAD

**Issue by saveli** [klahnakoski/mo-sql-parsing#31]
Both `minus` (Oracle) and `except` (Postgres) cause a `ParseException`:
```
from mo_sql_parsing import parse
sql = """select name from employee
minus
select 'Alan' from dual
"""
try:
    parse(sql)
except Exception as e:
    print(e)
```
`Expecting StringEnd, found "select 'Al" (at char 32, (line:3, col:1)	`

```
from mo_sql_parsing import parse
sql = """select name from employee
except
select 'Alan'
"""
try:
    parse(sql)
except Exception as e:
    print(e)
```
`Expecting StringEnd, found "select 'Al" (at char 33, (line:3, col:1)	`

**Comment by klahnakoski** [comment]
fixed https://github.com/klahnakoski/mo-sql-parsing/commit/b9bdfab2e74452b9a6e34fee33e71e38a8cf21e3
