### ISSUE TITLE
Formatter does not work for queries with INTERSECT/EXCEPT/UNION

### ISSUE THREAD

**Issue by aosokin** [klahnakoski/mo-sql-parsing#34]
With the recent addition of INTERSECT of #20 (Thanks a lot for that!), the format operation does not support queries with  INTERSECT/EXCEPT/UNION keywords:
```
import mo_sql_parsing as msp

query = "SELECT stuid FROM student INTERSECT SELECT stuid FROM student"
d = msp.parse(query)
back = msp.format(d)
```
`msp.format(d)` returns an empty string

**Comment by klahnakoski** [comment]
I am working on this.

**Comment by aosokin** [comment]
Thanks a lot for such a quick fix!
