### ISSUE TITLE
Test formatter agaist 3rd party SQL

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/mo-sql-parsing#38]
Copying large blocks of SQL from other projects is a good source of tests data.  Here are some sources, as per https://github.com/klahnakoski/mo-sql-parsing/issues/37:

I'm trying to use your parser for several datasets for the task of translating English text to SQL queries:
- [Spider](https://yale-lily.github.io/spider), queries [here](https://github.com/yandex-research/sparqling-queries/blob/master/data/spider/dev_gold.sql) and [here](https://raw.githubusercontent.com/yandex-research/sparqling-queries/master/data/spider/train_gold.sql)
- ATIS dataset, queries [here](https://github.com/sriniiyer/nl2sql/blob/master/data/atis/dev.sql), [here](https://github.com/sriniiyer/nl2sql/blob/master/data/atis/test.sql), [here](https://raw.githubusercontent.com/sriniiyer/nl2sql/master/data/atis/train_dev.sql)
- Geography dataset, queries [here](https://github.com/sriniiyer/nl2sql/blob/master/data/geo/geo_dev.sql), [here](https://github.com/sriniiyer/nl2sql/blob/master/data/geo/geo_test.sql), [here](https://github.com/sriniiyer/nl2sql/blob/master/data/geo/geo_train.sql), [here](https://github.com/sriniiyer/nl2sql/blob/master/data/geo/geo_tr.sql)

**Comment by aosokin** [comment]
Found two more in these sources:

`SELECT hire_date FROM employees WHERE first_name NOT LIKE '%M%'`
incorrectly becomes
`SELECT hire_date FROM employees WHERE first_name NOT_LIKE '%M%'`

and 

on `SELECT document_name FROM documents GROUP BY document_type_code ORDER BY count(*) DESC LIMIT 3 INTERSECT SELECT document_name FROM documents GROUP BY document_structure_code ORDER BY count(*) DESC LIMIT 3` the parser crashes

**Comment by klahnakoski** [comment]
Good enough for now.
