### ISSUE TITLE
mo_parsing.exceptions.ParseException: Expecting {offset} | {StringEnd}, found "INTERSECT " (at char 95), (line:1, col:96)

### ISSUE THREAD

**Issue by 22842219** [klahnakoski/mo-sql-parsing#39]
Hi there, 
I've got the following error. Could you advise me about it? Please see below detail. Thanks a lot. 

----error message ----
mo_parsing.exceptions.ParseException: Expecting {offset} | {StringEnd}, found "INTERSECT " (at char 95), (line:1, col:96)

----SQL query that is ready to be parsed----
SELECT document_name FROM documents GROUP BY document_type_code ORDER BY count(*) DESC LIMIT 3 INTERSECT SELECT document_name FROM documents GROUP BY document_structure_code ORDER BY count(*) DESC LIMIT 3
T

Best,
Zea

**Comment by klahnakoski** [comment]
sorry for the delay, looking...

**Comment by klahnakoski** [comment]
that is invalid SQL: INTERSECT can not follow ORDER BY (or LIMIT, OR UNTIL)

**Comment by klahnakoski** [comment]
you can try the query here for a better error explanation:  https://sqliteonline.com/
