### ISSUE TITLE
Incorrect formatting of the  CAST('value' AS TYPE)

### ISSUE THREAD

**Issue by gabriellevlima** [klahnakoski/mo-sql-parsing#44]
from mo_sql_parsing import parse
from mo_sql_parsing import format
format(parse("select cast(10.008 AS DECIMAL(10,2))"))
The resulting is "SELECT CAST(10.008, DECIMAL(10, 2))", without "AS"

**Comment by klahnakoski** [comment]
Thank you for reporting this.  I will work on it this week,

**Comment by klahnakoski** [comment]
fixed here, with an unfortunate commit message:

https://github.com/klahnakoski/mo-sql-parsing/commit/de4ee44d1eedf1a20616ab1c691c9b38f3d89965
