### ISSUE TITLE
The format for cast(col as FLOAT) not work as expected for as

### ISSUE THREAD

**Issue by LenaJava** [klahnakoski/mo-sql-parsing#45]
q = "select node,datetime from eutrancellfdd where ((900 - ( cast(pmCellDowntimeAuto as FLOAT) + cast(pmCellDowntimeMan as FLOAT) ) ) / 900) < 0.9 order by datetime limit 100"
parsed_query = parse_mysql(q)
print(f"parsed_query: {parsed_query}")
re_format_query= format(parsed_query)
print(f"re_format_query: {re_format_query}")

parsed_query: {'select': [{'value': 'node'}, {'value': 'datetime'}], 'from': 'eutrancellfdd', 'where': {'lt': [{'div': [{'sub': [900, {'add': [{'cast': ['pmCellDowntimeAuto', {'float': {}}]}, {'cast': ['pmCellDowntimeMan', {'float': {}}]}]}]}, 900]}, 0.9]}, 'orderby': {'value': 'datetime'}, 'limit': 100}

re_format_query: SELECT node, datetime FROM eutrancellfdd WHERE 900 - (CAST(pmCellDowntimeAuto, FLOAT()) + CAST(pmCellDowntimeMan, FLOAT())) / 900 < 0.9 ORDER BY datetime LIMIT 100

**Comment by klahnakoski** [comment]
This has been fixed, and released, the other day: https://pypi.org/project/mo-sql-parsing/7.4.21313/

I added a test, just in case: https://github.com/klahnakoski/mo-sql-parsing/commit/3a343424c7ecd1fd133843fb51919651feb648bd#diff-77e357ea1ebd625dbc52532a43f82e67a856e499d3d0b1427b57a71c6f85056aR583

**Comment by LenaJava** [comment]
that's great, thanks a lot for quick reply.

**Comment by LenaJava** [comment]
hi Prime:
One mor request, could you help anonymize the query in the newly added testcase?
Kindy change the query to something like:
"SELECT c1, c2 FROM t1 WHERE ((900 - (CAST(c3 AS FLOAT) + CAST(c4 AS FLOAT))) / 900) < 0.9 ORDER BY c2 LIMIT 100"

Thanks a lot.

**Comment by klahnakoski** [comment]
names removed
