### ISSUE TITLE
parse and format query are not works as expection

### ISSUE THREAD

**Issue by LenaJava** [klahnakoski/mo-sql-parsing#47]
hi all:
This is similar but more issue with #close45, I'm afraid the 45 issue is not fully solved in 7.4.21313 based on our test.
Take below query for example:
q = "SELECT c1, c2 FROM t1 WHERE ((900 - (CAST(c3 AS FLOAT) + CAST(c4 AS FLOAT))) / 900) < 0.9 ORDER BY c2 LIMIT 100"
parsed_query = parse_mysql(q)
print(f"parsed_query={parsed_query}")

formatted_query = format(parsed_query)
print(f"formatted_query={formatted_query}")

new_parsed_query = parse_mysql(formatted_query)
print(f"formatted_query={new_parsed_query}")
---------------------------------------------------------------
**Issues:**
1.  the result for the parsed_query  and formatted_query is as blow. the "()" after c3 AS FLOCAT in formatted_query should not expected.
parsed_query={'select': [{'value': 'c1'}, {'value': 'c2'}], 'from': 't1', 'where': {'lt': [{'div': [{'sub': [900, {'add': [{'cast': ['c3', {'float': {}}]}, {'cast': ['c4', {'float': {}}]}]}]}, 900]}, 0.9]}, 'orderby': {'value': 'c2'}, 'limit': 100}
formatted_query=SELECT c1, c2 FROM t1 WHERE 900 - (CAST(c3 AS FLOAT**()**) + CAST(c4 AS FLOAT**()**)) / 900 < 0.9 ORDER BY c2 LIMIT 100

2. after invoking parsed_query=parse_mysql(q), formatted_query=format(parsed_query), and new_parsed_query=parse_mysql(formatted_query), the expectation is new_parsed_query==q,
To be clear, the expected result should match one of the following:
SELECT c1, c2 FROM t1 WHERE ((900 - (CAST(c3 AS FLOAT) + CAST(c4 AS FLOAT))) / 900) < 0.9 ORDER BY c2 LIMIT 100
SELECT c1, c2 FROM t1 WHERE (900 - (CAST(c3 AS FLOAT) + CAST(c4 AS FLOAT))) / 900 < 0.9 ORDER BY c2 LIMIT 100

3. An exception is raised when invoking "new_parsed_query = parse_mysql(formatted_query)"
---------------------------------------------------------------------------
ParseException                            Traceback (most recent call last)
~\Anaconda3\lib\site-packages\mo_parsing\expressions.py in parse_impl(self, string, start, do_actions)
    504             try:
--> 505                 result = e._parse(string, start, do_actions)
    506                 return ParseResults(

~\Anaconda3\lib\site-packages\mo_parsing\core.py in _parse(self, string, start, do_actions)
    450         try:
--> 451             result = self.parse_impl(string, start, do_actions)
    452         except Exception as cause:

~\Anaconda3\lib\site-packages\mo_parsing\expressions.py in parse_impl(self, string, start, do_actions)
    280                 else:
--> 281                     raise pe
    282 

~\Anaconda3\lib\site-packages\mo_parsing\expressions.py in parse_impl(self, string, start, do_actions)
    268             try:
--> 269                 result = expr._parse(string, index, do_actions)
    270                 acc.append(result)

~\Anaconda3\lib\site-packages\mo_parsing\core.py in _parse(self, string, start, do_actions)
    450         try:
--> 451             result = self.parse_impl(string, start, do_actions)
    452         except Exception as cause:

~\Anaconda3\lib\site-packages\mo_parsing\expressions.py in parse_impl(self, string, start, do_actions)
    280                 else:
--> 281                     raise pe
    282 

~\Anaconda3\lib\site-packages\mo_parsing\expressions.py in parse_impl(self, string, start, do_actions)
    268             try:
--> 269                 result = expr._parse(string, index, do_actions)
    270                 acc.append(result)

~\Anaconda3\lib\site-packages\mo_parsing\core.py in _parse(self, string, start, do_actions)
    450         try:
--> 451             result = self.parse_impl(string, start, do_actions)
    452         except Exception as cause:

~\Anaconda3\lib\site-packages\mo_parsing\tokens.py in parse_impl(self, string, start, do_actions)
    234             )
--> 235         raise ParseException(self, start, string)
    236 

ParseException: Expecting union, found "- (CAST(c3" (at char 32), (line:1, col:33)

The above exception was the direct cause of the following exception:

ParseException                            Traceback (most recent call last)
ParseException: Expecting {union} | {intersect} | {except} | {minus}, found "- (CAST(c3" (at char 32), (line:1, col:33)

The above exception was the direct cause of the following exception:

ParseException                            Traceback (most recent call last)
<ipython-input-7-7cc13e353797> in <module>
      7 print(f"formatted_query={formatted_query}")
      8 
----> 9 new_parsed_query = parse_mysql(formatted_query)
     10 # print(f"formatted_query={new_parsed_query}")

~\Anaconda3\lib\site-packages\mo_sql_parsing\__init__.py in parse_mysql(sql, null, calls)
     50         if not mysql_parser:
     51             mysql_parser = sql_parser.mysql_parser()
---> 52         return _parse(mysql_parser, sql, null, calls)
     53 
     54 

~\Anaconda3\lib\site-packages\mo_sql_parsing\__init__.py in _parse(parser, sql, null, calls)
     60     utils.scrub_op = calls
     61     sql = sql.rstrip().rstrip(";")
---> 62     parse_result = parser.parse_string(sql, parse_all=True)
     63     output = scrub(parse_result)
     64     for o, n in utils.null_locations:

~\Anaconda3\lib\site-packages\mo_parsing\core.py in output(*args, **kwargs)
     77                     Log.error("reset action failed", cause=e)
     78 
---> 79             return func(*args, **kwargs)
     80 
     81     return output

~\Anaconda3\lib\site-packages\mo_parsing\core.py in parse_string(self, string, parse_all)
    133 
    134         """
--> 135         return self._parseString(string, parse_all=parse_all)
    136 
    137     def _parseString(self, string, parse_all=False):

~\Anaconda3\lib\site-packages\mo_parsing\core.py in _parseString(self, string, parse_all)
    153                 return tokens.tokens[0]
    154         except ParseException as cause:
--> 155             raise cause.best_cause
    156 
    157     @entrypoint

ParseException: Expecting {union} | {intersect} | {except} | {minus} | {order} | {limit} | {offset} | {StringEnd}, found "- (CAST(c3" (at char 32), (line:1, col:33)

**Comment by klahnakoski** [comment]
added test:  https://github.com/klahnakoski/mo-sql-parsing/commit/128de193e8b9182261be69b1d39d6e900d8508e8#diff-77e357ea1ebd625dbc52532a43f82e67a856e499d3d0b1427b57a71c6f85056aR615

**Comment by klahnakoski** [comment]
pushed new version with this fix   https://pypi.org/project/mo-sql-parsing/8.2.21318/
