### ISSUE TITLE
Parse and format is not correct for DISTICT keyword

### ISSUE THREAD

**Issue by LenaJava** [klahnakoski/mo-sql-parsing#49]
hi, Primes:
This maybe not correct for the DISTICT parse and format. Could you please help for a look? Thanks.

q = "select DISTICT col_a, col_b from table_test"
pasred_query = parse_mysql(q)
print(f"parsed_query: {pasred_query}")
re_format_query = format(parsed_query)
print(f"re_format_query: {re_format_query}")

parsed_query: {'select': [{'value': 'DISTICT', 'name': 'col_a'}, {'value': 'col_b'}], 'from': 'table_test'}
re_format_query: 'SELECT DISTICT AS col_a, col_b FROM table_test'

**Comment by klahnakoski** [comment]
DISTINCT is spelt wrong
