### ISSUE TITLE
Incorrect formatting of  Interval

### ISSUE THREAD

**Issue by gabriellevlima** [klahnakoski/mo-sql-parsing#51]
from mo_sql_parsing import parse
from mo_sql_parsing import format
format(parse("select now() + interval 2 week"))
The resulting is "SELECT NOW() + INTERVAL(2, week)"

**Comment by klahnakoski** [comment]
test added here https://github.com/klahnakoski/mo-sql-parsing/commit/f61ee630e20d0d4331659088eb20b3a9ed9e659f#diff-77e357ea1ebd625dbc52532a43f82e67a856e499d3d0b1427b57a71c6f85056aR653

fixed https://pypi.org/project/mo-sql-parsing/8.5.21328/
