### ISSUE TITLE
parsing error when using squared bracket in from

### ISSUE THREAD

**Issue by Ventrilok** [klahnakoski/mo-sql-parsing#52]
Hello, 

 I'm looking at using your lib to deduplicate queries in a large inventory of Ms SQL Server based queries made by 100 of users.

While parsing our inventory I've encounter the following error:
ParseException: Expecting table_source, found "[myDB].[my" (at char 49), (line:1, col:50)

You can use this sample query to replicate the issue:
`SELECT [Timestamp] ,[RowsCount] ,[DataName]  FROM [myDB].[myTable] where [Timestamp] >='2020-01-01' and [Timestamp]<'2020-12-31'`

I hope you can include this use case in your lib, in the meantime, I'm doing some clean-up before using your parser.

thanks for your work !

**Comment by klahnakoski** [comment]
@Ventrilok   please use `from mo_sql_parsing import parse_sqlserver as parse` 

Example: https://github.com/klahnakoski/mo-sql-parsing/blob/dev/tests/test_sql_server.py#L13

Verified here: https://github.com/klahnakoski/mo-sql-parsing/commit/2a50052e6696d6429f4cdade7e3fb6cdb49763d1

**Comment by klahnakoski** [comment]
It would be nice to detect the sql flavour so you need not do the work of selecting a matching parser.
