### ISSUE TITLE
Support binary Operators after Window Statement

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#57]
Hello,

we have been using your library for a while to parse our queries and are super happy that it exists. During the last half year (we started with moz-sql-parser, right before you started not updating it anymore and did not realise that), we collected a bunch of test cases that the parser does not understand and we are kinda painfully fixing by adding a preprocessor to our code. I will include the preprocessor's statements here, I think they are self-explanatory. I will open one issue per test case

```py
# NULLS FIRST/LAST is not understood.
fail = 'SELECT X() OVER () = 1 AS is_true'
success = """
SELECT
    X() OVER ()
    /* parser-replace: */= 1/* end:parser-replace */ AS is_true
"""
```

I would be happy to help out fixing them, but could probably use one or two pointers where to start :slightly_smiling_face: 

Our engine is PrestoDB (Athena), but that should be covered by this issue as far as I understood.

**Comment by klahnakoski** [comment]
Fixed.

Test is here: https://github.com/klahnakoski/mo-sql-parsing/blob/57dcf1c865fd7f2c504e29f4819a3598e1e21bbe/tests/test_athena.py

Version deployed: https://pypi.org/project/mo-sql-parsing/8.6.21337/
