### ISSUE TITLE
Support IS DISTINCT FROM

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#59]
Engine: PrestoDB/Athena [IS DISTINCT FROM](https://prestodb.io/docs/current/functions/comparison.html#is-distinct-from-and-is-not-distinct-from)

```py
fails = 'SELECT 1 IS DISTINCT FROM 2'
succeeds = """
    SELECT 1
    /* parser-replace: */IS DISTINCT FROM 2/* end:parser-replace */
"""
```

Thanks again!

**Comment by klahnakoski** [comment]
I am not sure about how to parse `IS DISTINCT`.  Are there some examples in the wild you can link to?

**Comment by klahnakoski** [comment]
... I see I missed your link.  Thank you

**Comment by klahnakoski** [comment]
fixed here: https://github.com/klahnakoski/mo-sql-parsing/commit/e3742489c156681da243191fbf2245d2bc6f5ec4#diff-194d32a239132f3ee212d5ca5824f691a87e0b70df1f7c074e3d887b2bdfa15aR76

**Comment by klahnakoski** [comment]
found here https://pypi.org/project/mo-sql-parsing/8.7.21338/

**Comment by sbrandtb** [comment]
@klahnakoski Thanks a lot, again! I will try it out first thing monday morning 🙂
