### ISSUE TITLE
Support Structural Data Types as Cast Target

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#60]
Engine: PrestoDB/Athena [Structural Types](https://prestodb.io/docs/current/language/types.html#structural)

```py
fails = 'SELECT CAST(x AS ROW(y VARCHAR))'
succeeds = """
    SELECT CAST(
        x AS /* parser-replace: VARCHAR */ROW(y VARCHAR)
        /* end:parser-replace */
    )
"""
```

More information:

* Nested types lke `ARRAY(ROW(y VARCHAR))` should also work - in fact, this is our use case

Thanks again!

**Comment by klahnakoski** [comment]
fixed here https://github.com/klahnakoski/mo-sql-parsing/commit/362f056a9e7e84d05e07b13f50997b9ec4fda674#diff-194d32a239132f3ee212d5ca5824f691a87e0b70df1f7c074e3d887b2bdfa15aR60

**Comment by sbrandtb** [comment]
@klahnakoski Thanks again for the super fast response and fix! However, nested types do not seem to work yet: `SELECT CAST(x AS ARRAY(ROW(y VARCHAR)))`
