### ISSUE TITLE
Support dot access after bracket access

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#61]
Engine: PrestoDB/Athena [Structural Types](https://prestodb.io/docs/current/language/types.html#structural)

```py
fails = "SELECT b['c'].d"
succeeds = "SELECT b['c']/* parser-replace: */.d/* end:parser-replace */"
```

This happens in our case when we have a map `b` of structs and want to access property `b` of the struct. It would be nice if that would also work with Arrays, but I did not test yet if that also fails. Might be a good test case: `SELECT b[0].d`

Thanks again!

**Comment by klahnakoski** [comment]
fixed here:  https://github.com/klahnakoski/mo-sql-parsing/commit/bf71672cced17c87357e05ef6bf29805d167f2f3#diff-194d32a239132f3ee212d5ca5824f691a87e0b70df1f7c074e3d887b2bdfa15aR70
