### ISSUE TITLE
Support *nested* Structural Data Types as Cast Target

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#62]
Hello again :slightly_smiling_face: 

This is a follow-up to #60, I figured it deserves a new issue:

```sql
SELECT CAST(x AS ARRAY(ROW(y VARCHAR)))
```

is not parsing. Looks like nested structural types are not supported. Other test cases would be

```sql
SELECT CAST(x AS ARRAY(ARRAY(VARCHAR)));
SELECT CAST(x AS ROW(y ARRAY(VARCHAR)));
```

Any wild combination goes :smile:

**Comment by klahnakoski** [comment]
fixed here: https://github.com/klahnakoski/mo-sql-parsing/commit/5520bed77f176268234ab7747fc2c79bbcd428d2#diff-194d32a239132f3ee212d5ca5824f691a87e0b70df1f7c074e3d887b2bdfa15aR92

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.10.21343/

**Comment by sbrandtb** [comment]
@klahnakoski thanks a lot, again :slightly_smiling_face:
