### ISSUE TITLE
Can mo-sql-parsing support table name with dashes?

### ISSUE THREAD

**Issue by LenaJava** [klahnakoski/mo-sql-parsing#63]
Currently the mo-sql-paring seems doesn't support table name with dashes. there has exception raised if there have dashes.
example:
**q = "select col from test-table"**

ParseException                            Traceback (most recent call last)
~\Anaconda3\lib\site-packages\mo_parsing\expressions.py in parse_impl(self, string, start, do_actions)
    504             try:
--> 505                 result = e._parse(string, start, do_actions)
    506                 return ParseResults(

~\Anaconda3\lib\site-packages\mo_parsing\core.py in _parse(self, string, start, do_actions)
    463             for fn in self.parse_action:
--> 464                 next_result = fn(result, result.start, string)
    465                 if next_result.end < result.end:

~\Anaconda3\lib\site-packages\mo_parsing\utils.py in wrapper(token, index, string)
    388             args = token, index, string
--> 389             result = func(*args[:num_args])
    390             if result is None:

~\Anaconda3\lib\site-packages\mo_sql_parsing\sql_parser.py in no_dashes(tokens, start, string)
     22         index = tokens[0].find("-")
---> 23         raise ParseException(
     24             tokens.type,

ParseException: Ambiguity: Use backticks (``) around identifiers with dashes, or add space around subtraction operator. (Regex:([\$@-Z_a-zÀ-ÖØ-öø-ƿ] + ({PrecededBy:([^ 0-9]) + - + LookAhead:([^ 0-9])} | {[\$0-9@-Z_a-zÀ-ÖØ-öø-ƿ]})*)), found "-table" (at char 20), (line:1, col:21)

The above exception was the direct cause of the following exception:

ParseException                            Traceback (most recent call last)
ParseException: Expecting Regex:([\$@-Z_a-zÀ-ÖØ-öø-ƿ] + ({PrecededBy:([^ 0-9]) + - + LookAhead:([^ 0-9])} | {[\$0-9@-Z_a-zÀ-ÖØ-öø-ƿ]})*), found "-table" (at char 20), (line:1, col:21)

The above exception was the direct cause of the following exception:

ParseException                            Traceback (most recent call last)
ParseException: Expecting Regex:([\$@-Z_a-zÀ-ÖØ-öø-ƿ] + ({PrecededBy:([^ 0-9]) + - + LookAhead:([^ 0-9])} | {[\$0-9@-Z_a-zÀ-ÖØ-öø-ƿ]})*), found "-table" (at char 20), (line:1, col:21)

The above exception was the direct cause of the following exception:

ParseException                            Traceback (most recent call last)
<ipython-input-10-100b5663aaad> in <module>
     13 
     14 q = "select col from test-table"
---> 15 parser = parse_mysql(q)
     16 print(f"parser: {parser}")
     17 # parser_with = parser.get("with")

~\Anaconda3\lib\site-packages\mo_sql_parsing\__init__.py in parse_mysql(sql, null, calls)
     51         if not mysql_parser:
     52             mysql_parser = sql_parser.mysql_parser()
---> 53         return _parse(mysql_parser, sql, null, calls)
     54 
     55 

~\Anaconda3\lib\site-packages\mo_sql_parsing\__init__.py in _parse(parser, sql, null, calls)
     76     utils.scrub_op = calls
     77     sql = sql.rstrip().rstrip(";")
---> 78     parse_result = parser.parse_string(sql, parse_all=True)
     79     output = scrub(parse_result)
     80     for o, n in utils.null_locations:

~\Anaconda3\lib\site-packages\mo_parsing\core.py in output(*args, **kwargs)
     77                     Log.error("reset action failed", cause=e)
     78 
---> 79             return func(*args, **kwargs)
     80 
     81     return output

~\Anaconda3\lib\site-packages\mo_parsing\core.py in parse(self, string, parse_all)
    139 
    140         """
--> 141         return self._parseString(string, parse_all=parse_all)
    142 
    143     parse_string = parse

~\Anaconda3\lib\site-packages\mo_parsing\core.py in _parseString(self, string, parse_all)
    161                 return tokens.tokens[0]
    162         except ParseException as cause:
--> 163             raise cause.best_cause from None
    164 
    165     @entrypoint

ParseException: Expecting Regex:([\$@-Z_a-zÀ-ÖØ-öø-ƿ] + ({PrecededBy:([^ 0-9]) + - + LookAhead:([^ 0-9])} | {[\$0-9@-Z_a-zÀ-ÖØ-öø-ƿ]})*), found "-table" (at char 20), (line:1, col:21)

**Comment by klahnakoski** [comment]
The best I can do is improve the error message

https://github.com/klahnakoski/mo-sql-parsing/commit/bbaf31c2a9a5029aead52098e63815b91b313d99#diff-6e5030d96839d3fe377cf209b6cab5b0d50ae900b458248d8c24b61774117170L70
