### ISSUE TITLE
Support INSERT INTO

### ISSUE THREAD

**Issue by JakobDev** [klahnakoski/mo-sql-parsing#64]
The following qury fails
```sql
INSERT INTO tab (name) VALUES(42)
```
with this error
```
mo_parsing.exceptions.ParseException: Expecting table, found "tab (name)" (at char 12), (line:1, col:13)
```

**Comment by klahnakoski** [comment]
test added.  Fixed:  https://github.com/klahnakoski/mo-sql-parsing/commit/f017186afc0d8cb3f218ad918348df27efff189c#diff-5592e672cef095f585fc0083c44cdfb8aafdfc11904a484dfa2b0794b0079f35R707

**Comment by klahnakoski** [comment]
Since Pypi is down in my region, it will be a while before this is deployed
