### ISSUE TITLE
format-function exports subquery in inner join without parenthesis, which makes parse-function fail

### ISSUE THREAD

**Issue by chufe-dremio** [klahnakoski/mo-sql-parsing#65]
When having the following query:

`Select * from abc a inner join (select * from def) b on a.id = b.id `

The parse function is able to parse it correctly, but when it then gets exported with `format` function, it does not export the brackets anymore for the sub-query:

`SELECT * FROM abc AS a INNER JOIN SELECT * FROM def AS b ON a.id = b.id`

The exported query cannot be read with `parse`-call and fails with the following error:

```
Traceback (most recent call last):
  File "src\testen.py", line 11, in <module>
    print(parse(s))
  File "venv\lib\site-packages\mo_sql_parsing\__init__.py", line 37, in parse
    result = _parse(common_parser, sql, null, calls)
  File "venv\lib\site-packages\mo_sql_parsing\__init__.py", line 78, in _parse
    parse_result = parser.parse_string(sql, parse_all=True)
  File "venv\lib\site-packages\mo_parsing\core.py", line 79, in output
    return func(*args, **kwargs)
  File "venv\lib\site-packages\mo_parsing\core.py", line 141, in parse
    return self._parseString(string, parse_all=parse_all)
  File "venv\lib\site-packages\mo_parsing\core.py", line 163, in _parseString
    raise cause.best_cause from None
mo_parsing.exceptions.ParseException: Expecting {union} | {intersect} | {except} | {minus} | {order by} | {limit} | {offset} | {StringEnd}, found "INNER JOIN" (at char 23), (line:1, col:24)
```

Below you can find the code to reproduce:

```
from mo_sql_parsing import parse
from mo_sql_parsing import format

sql = '''
Select * from abc a inner join (select * from def) b on a.id = b.id 
'''
p = parse(sql)
s = format(p)
print(s)
# Fails, the exported SQLshould also be readable.
print(parse(s))
```

**Comment by chufe-dremio** [comment]
Btw. I can see this function `def isolate(expr, sql, prec):` but it does not seem to be called.
`

**Comment by klahnakoski** [comment]
thank you, i have a fix here:  https://github.com/klahnakoski/mo-sql-parsing/commit/db6101f3dc35cadf91d6173e712726cb63ae5e68#diff-77e357ea1ebd625dbc52532a43f82e67a856e499d3d0b1427b57a71c6f85056aR658

Pypi was down a little while ago, I will try to deploy again

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.14.21350/

**Comment by klahnakoski** [comment]
> I can see this function def isolate(expr, sql, prec): but it does not seem to be called.

Thank you for looking into this!  In general, the formatter calls itself with a "precedence" (read "operator precedence").  This value is used to determine if callee should add parenthesis.  In general, I simply make some guesses about what value will give the  parenthesis I need, or not.  The most important work is pointing out the problem, and having it recorded as a test.

Thank you for submitting an issue, the formatter is now better for everyone.
