### ISSUE TITLE
format-function exports IN-clause without parenthesis, which makes query invalid for DB

### ISSUE THREAD

**Issue by chufe-dremio** [klahnakoski/mo-sql-parsing#66]
When having the following query:

`SELECT * FROM my_table WHERE outcome NOT IN ('COMPLETED') `

The parse function is able to parse it correctly, but when it then gets exported with `format` function, it does not export the parenthesis for IN clause which cause issues in DB systems to parse the query:

`SELECT * FROM my_table WHERE outcome NOT IN 'COMPLETED'`

Below you can find the code to reproduce:

```
from mo_sql_parsing import parse
from mo_sql_parsing import format

sql = "SELECT * FROM my_table WHERE outcome NOT IN ('COMPLETED')"
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)
```

Output:

```
ORIG: SELECT * FROM my_table WHERE outcome NOT IN ('COMPLETED')
NEW: SELECT * FROM my_table WHERE outcome NOT IN 'COMPLETED'
```

**Comment by chufe-dremio** [comment]
Just to add this seems only to appear when IN clause has one value

**Comment by klahnakoski** [comment]
Thank you again.  If you have not guessed by now, the formatter is not as good as the parser.  Please continue sending reports.  

Fixed here: https://github.com/klahnakoski/mo-sql-parsing/commit/87b077405786183a9e8a24a73a4a8a3461c11996#diff-f2091b143f4ef833f07602a4b368499a5237194490913c78381387a68a077791R298

https://pypi.org/project/mo-sql-parsing/8.16.21352/

**Comment by chufe-dremio** [comment]
Thanks for fixing it that quickly.
