### ISSUE TITLE
TRIM function with additional parameters fails to parse

### ISSUE THREAD

**Issue by chufe-dremio** [klahnakoski/mo-sql-parsing#67]
For many DB systems the trim function can take additional arguments (e.g. Postgres, Dremio):

The syntax is like:

`TRIM([LEADING | TRAILING | BOTH] [characters] FROM string)`

e.g.

`TRIM(LEADING FROM string)`

More examples can be found in the code block below. When using a TRIM like above the parser fails.

More here: https://www.postgresqltutorial.com/postgresql-trim-function/

```
from mo_sql_parsing import parse
from mo_sql_parsing import format


sql = "SELECT TRIM(BOTH FROM column1) FROM my_table"
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)

sql = "SELECT TRIM(TRAILING FROM column1) FROM my_table"
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)

sql = "SELECT TRIM(LEADING FROM column1) FROM my_table"
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)

sql = "SELECT TRIM(TRAILING '.1' from column1) FROM my_table"
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)

sql = "SELECT TRIM(LEADING '.1' from column1) FROM my_table"
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)

sql = "SELECT TRIM(BOTH '.1' from column1) FROM my_table"
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)

# With embedded trim function
sql = "SELECT TRIM('.1' from TRIM(column1)) FROM my_table"
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)
```

**Comment by chufe-dremio** [comment]
Also MySQL is using this syntax:
https://www.w3resource.com/mysql/string-functions/mysql-trim-function.php

**Comment by klahnakoski** [comment]
thank you for all the examples.  they made a good test suite:

fixed here:  https://github.com/klahnakoski/mo-sql-parsing/commit/949598265eb5d121d3b3b80831e83cf834fc84ad#diff-61d5a1a018e97cc478eba974e6abfff036bf58e449578b7b680fab7f2e63976dR1443
