### ISSUE TITLE
When using numbers with multiple values in IN-clause the grouping for numbers is ignored (parenthesis removed).

### ISSUE THREAD

**Issue by chufe-dremio** [klahnakoski/mo-sql-parsing#68]
The first block with strings works correctly:

```
from mo_sql_parsing import parse
from mo_sql_parsing import format

sql = "SELECT * FROM AirlineFlights WHERE (origin, dest) IN (('ATL', 'ABE'), ('DFW', 'ABI'))"
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)
```

Output:

```
ORIG: SELECT * FROM AirlineFlights WHERE (origin, dest) IN (('ATL', 'ABE'), ('DFW', 'ABI'))
NEW: SELECT * FROM AirlineFlights WHERE (origin, dest) IN (('ATL', 'ABE'), ('DFW', 'ABI'))
```
When using numbers in the same construct, it parenthesis for the grouping is removed:

```
sql = "SELECT * FROM mytable WHERE (a, b) IN ((1, 2), (3,4))"
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)
```

Output:

```
ORIG: SELECT * FROM mytable WHERE (a, b) IN ((1, 2), (3,4))
NEW: SELECT * FROM mytable WHERE (a, b) IN (1, 2, 3, 4)
```

**Comment by klahnakoski** [comment]
fixed here: https://github.com/klahnakoski/mo-sql-parsing/commit/c7df2926f45b0cb80ca3a044460ad67d9248d2d4#diff-77e357ea1ebd625dbc52532a43f82e67a856e499d3d0b1427b57a71c6f85056aR688

found another issue, but it is not terrible: https://github.com/klahnakoski/mo-sql-parsing/commit/c7df2926f45b0cb80ca3a044460ad67d9248d2d4#diff-61d5a1a018e97cc478eba974e6abfff036bf58e449578b7b680fab7f2e63976dR1550
