### ISSUE TITLE
Formatter translates square bracket to GET function

### ISSUE THREAD

**Issue by chufe-dremio** [klahnakoski/mo-sql-parsing#69]
Some database systems provide complex column objects, which can contain fields or lists. List can be accessed using square brackets, e.g.:

`SELECT nested_0.parentsList.datasetPathList[2] FROM mytable_with_complex_cols`

The good news is, it can be parsed, but for some reason the formatting introduces a GET function. 
If the formatted output should be the same as the input.

```
from mo_sql_parsing import parse
from mo_sql_parsing import format

sql = """SELECT nested_0.parentsList.datasetPathList[2] FROM mytable_with_complex_cols"""
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)
```
Output:

ORIG: SELECT nested_0.parentsList.datasetPathList[2] FROM mytable_with_complex_cols
NEW: SELECT GET(nested_0.parentsList.datasetPathList, 2) FROM mytable_with_complex_cols

**Comment by klahnakoski** [comment]
fixed here: https://github.com/klahnakoski/mo-sql-parsing/commit/14679f98222afa56d68b8fe5b8a19fcd16013964#diff-77e357ea1ebd625dbc52532a43f82e67a856e499d3d0b1427b57a71c6f85056aR722
