### ISSUE TITLE
Parsed LIMIT is translated to 'FETCH x ROWS ONLY' in format

### ISSUE THREAD

**Issue by chufe-dremio** [klahnakoski/mo-sql-parsing#71]
Thanks for fixing everything so quickly.
Probably this was introduced with #70 
Not all database systems understand 'FETCH x ROWS ONLY' and 'limit'. From JSON it is now always translated to 'FETCH'

```
from mo_sql_parsing import parse
from mo_sql_parsing import format

sql = "SELECT * FROM my_table LIMIT 10"

p = parse(sql)
s = format(p)
print("ORIG: " + sql)
# print("----")
print("NEW: " + s)
```

Output:

```
ORIG: SELECT * FROM my_table LIMIT 10
NEW: SELECT * FROM my_table FETCH 10 ROWS ONLY
```

The second problem is that the clause needs to be "FETCH NEXT" instead of just "FETCH":

```
sql = "SELECT * FROM mytable FETCH NEXT 20 ROWS ONLY"

p = parse(sql)
s = format(p)
print("ORIG: " + sql)
# print("----")
print("NEW: " + s)
```

Output:

```
ORIG: SELECT * FROM mytable FETCH NEXT 20 ROWS ONLY
NEW: SELECT * FROM mytable FETCH 20 ROWS ONLY
```
The database system I'm testing with refuses the query when "NEXT" is missing.

**Comment by klahnakoski** [comment]
yes, good point. I had hoped to avoid the extra 'bit' of information required to store the difference between LIMIT and FETCH. 

The solution would be to store LIMIT and FETCH as separate items, even though they are the same thing

**Comment by klahnakoski** [comment]
Revert done here: https://github.com/klahnakoski/mo-sql-parsing/commit/2c27eb4cb7a81e09d68b3dcacd5413c576a463ac

**Comment by klahnakoski** [comment]
Leave the problem for later:  https://github.com/klahnakoski/mo-sql-parsing/issues/72

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.18.21356/

**Comment by chufe-dremio** [comment]
Thanks

Just a question, in the past I got also a new mo-parsing version, is this mo-parsing 8.17 correct?
![image](https://user-images.githubusercontent.com/85165302/147098215-f92ad1e3-744a-478c-ae47-e51d7b08eb44.png)

**Comment by klahnakoski** [comment]
yes, the mo-parsing version is correct.

Some of the problems that come up with this parser are a problem in mo-parsing, so you will see the two versions increase together.  In this case, the small change on mo-sql-parsing did not require a change in mo-parsing, so the old version is fine.

This versioning has been automated:  All-my-modules are scanned for changes, a dependency tree is calculated, and any modules requiring an upgrade are run through tests with their (new) dependencies before being deployed.  The automated deployment process has caught many of my own manual deployment mistakes.  Never again.
