### ISSUE TITLE
Incorrect formatting of the EXTRACT(unit FROM TIMESTAMP / DATE ts)

### ISSUE THREAD

**Issue by gabriellevlima** [klahnakoski/mo-sql-parsing#73]
from mo_sql_parsing import parse
from mo_sql_parsing import format
format(parse("SELECT EXTRACT(DAY FROM DATE'2019-08-17')"))
The resulting is "SELECT EXTRACT(day, DATE('2019-08-17'))", without "FROM"  and return the date with parentheses.

**Comment by klahnakoski** [comment]
fixed here https://github.com/klahnakoski/mo-sql-parsing/commit/70fba08b82e3eeb894e96ba6c2932853fcd248b9#diff-77e357ea1ebd625dbc52532a43f82e67a856e499d3d0b1427b57a71c6f85056aR727

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.24.21357/

**Comment by klahnakoski** [comment]
I will continue to look into the parenthesis, what database is this SQL for?

**Comment by gabriellevlima** [comment]
> I will continue to look into the parenthesis, what database is this SQL for?

Impala.
