### ISSUE TITLE
Support Multiline-Comments

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#75]
Hello, it's me again :sweat_smile: 

It looks like multiline comments are not supported at all. We only discovered this now since we consider their use highly discouraged, but I am reporting the bug nonetheless. All of the following cases fail, no matter which whitespaces used.

```py
[
            '/* foo */ SELECT TRUE',
            'SELECT /* foo */ TRUE',
            'SELECT TRUE /* foo */',
            '/* foo */\nSELECT TRUE',
]
```

The engine in our case is PrestoDB/Athena again, but Postgres and MySQL support those comments as well.

**Comment by klahnakoski** [comment]
fixed here:   https://github.com/klahnakoski/mo-sql-parsing/commit/3a149841ec4ea5864da072ef77d1e1488ceb103b#diff-61d5a1a018e97cc478eba974e6abfff036bf58e449578b7b680fab7f2e63976dR1586

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.25.22004/

**Comment by sbrandtb** [comment]
Thanks a lot!
