### ISSUE TITLE
SELECT TOP (1000) * fails to parse once used inside query with subquery

### ISSUE THREAD

**Issue by rostykob** [klahnakoski/mo-sql-parsing#78]
Hello,
Issue occurs when parsing query that contains a subquery. 
Example:
```
SELECT TOP 1000 *
FROM (
        SELECT result
        FROM dbo.b AS B
    ) AS X
WHERE expected <> result
```
If query does not contains a subquery parsing works.
Query:
```
SELECT TOP 1000 * FROM A
```
Result:
```
{
    'top': 1000,
    'select': '*',
    'from': 'A'
}
```
The above query `SELECT TOP 1000 * FROM (SELECT result  FROM dbo.b AS B)  X  WHERE expected <> result` also works if `*` replaced by any letter f.e `a`

**Comment by klahnakoski** [comment]
fixed here: https://github.com/klahnakoski/mo-sql-parsing/commit/935457a1956e5b69c91af574bd1974f48a3df1c3#diff-e00ab716ce5b907f9837cf090cc94d2f1f84c58145be20a49fcba3f453491ff6R119

**Comment by klahnakoski** [comment]
i will release tonight, my "automated" deploy has a bug

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.129.22027/

**Comment by rostykob** [comment]
Thank you Kyle! You are doing awesome job!
