### ISSUE TITLE
Cannot parse WITH (NOLOCK)

### ISSUE THREAD

**Issue by danielparton** [klahnakoski/mo-sql-parsing#79]
Hi, thanks for this library!
Unfortunately, it's failing for SQL Server queries with the NOLOCK command.

```.py
from mo_sql_parsing import parse_sqlserver

sql = '''
SELECT col1
FROM table1 WITH (NOLOCK)
'''

parsed = parse_sqlserver(sql)
```

Output:

```
mo_parsing.exceptions.ParseException: Expecting {union} | {intersect} | {except} | {minus} | {order by} | {offset} | {fetch} | {limit} | {StringEnd}, found "WITH NOLOC" (at char 25), (line:3, col:13)
```

If I remove the `WITH (NOLOCK)` statement then it runs fine.

**Comment by danielparton** [comment]
Also noting that the SQL Server functions CROSS APPLY and OUTER APPLY fail to parse.

**Comment by klahnakoski** [comment]
fixed "with nolock":  https://github.com/klahnakoski/mo-sql-parsing/commit/5e01d787179f4fd9ebf61f8c31488256b53bc6a6#diff-e00ab716ce5b907f9837cf090cc94d2f1f84c58145be20a49fcba3f453491ff6R143

working on the other....

**Comment by klahnakoski** [comment]
fixed: https://github.com/klahnakoski/mo-sql-parsing/commit/05ff7514236d3c55465a10d07642c6ecd37acd1a#diff-e00ab716ce5b907f9837cf090cc94d2f1f84c58145be20a49fcba3f453491ff6R157
