### ISSUE TITLE
Formatter translates CONCAT to || function

### ISSUE THREAD

**Issue by chufe-dremio** [klahnakoski/mo-sql-parsing#81]
When a query was parsed using CONCAT, it should be outputted with CONCAT as well. In Dremio for example the CONCAT function takes any type, but when using || for concatenation it always needs to be a varchar.

```
from mo_sql_parsing import parse
from mo_sql_parsing import format

sql = "SELECT concat('str1', 'str2', my_int_field) from testtable"
p = parse(sql)
s = format(p)
print("ORIG: " + sql)
print("NEW: " + s)
```

Output:

```
ORIG: SELECT concat('str1', 'str2', my_int_field) from testtable
NEW: SELECT 'str1' || 'str2' || my_int_field FROM testtable
```

So the NEW query would fail in Dremio, because it now needs an explicit casting to VARCHAR, but better option would be outputting it as a CONCAT again.

**Comment by klahnakoski** [comment]
My solution is to let `||` remain `concat()` when formatting.  Both get parsed to `concat`, and the information is already lost at that point.

https://github.com/klahnakoski/mo-sql-parsing/commit/45d4477627bc94ff7d266db781980394b679bdac#diff-77e357ea1ebd625dbc52532a43f82e67a856e499d3d0b1427b57a71c6f85056aR733

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.134.22048/

**Comment by chufe-dremio** [comment]
Thanks for fixing that quickly.
