### ISSUE TITLE
Parsing failing on "INSERT INTO ... RETURNING"

### ISSUE THREAD

**Issue by marijnvriens** [klahnakoski/mo-sql-parsing#83]
Passing the following string to parse() 

`INSERT INTO "some_table" ("some_A", "some_B") VALUES ('Foo', 'Bar') RETURNING "some_table"."id"
`
Raises: 
`mo_parsing.exceptions.ParseException: Expecting {,} | {StringEnd}, found "RETURNING " (at char 68), (line:1, col:69)`

Reference of the syntax: https://www.postgresql.org/docs/13/dml-returning.html

**Comment by klahnakoski** [comment]
Thank you very much for the reference!  I will work on it over the next day, or so.

**Comment by klahnakoski** [comment]
Fixed  https://github.com/klahnakoski/mo-sql-parsing/commit/3ebe1fbe4c937d4c206f35c8a0e914b84e9a3537#diff-c27809480953c5908cdc63856a3e545a7fd67d739492c0968b61f5090a107b0cR226

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.145.22062/
