### ISSUE TITLE
Error Parsing With INTERSECT

### ISSUE THREAD

**Issue by PosoSAgapo** [klahnakoski/mo-sql-parsing#84]
Thank you for contributing this awesome repository, but I have met a parsing error in the following SQL query:
`SELECT document_name FROM documents GROUP BY document_type_code ORDER BY count ( * ) DESC LIMIT 3 INTERSECT SELECT document_name FROM documents GROUP BY document_structure_code ORDER BY count ( * ) DESC LIMIT 3
`
The error reports `Expecting {offset} | {fetch} | {StringEnd}, found "INTERSECT "`. I am not very familiar with the mechanism of this parser, is it possible to resolve this problem?

**Comment by klahnakoski** [comment]
I will look at this today.

**Comment by klahnakoski** [comment]
The problem appears to be in the query:  `INTERSECT` can not follow `ORDER BY`.

*If* this can be parsed, then I am unclear on which way it should parse:

* `(SELECT ... LIMIT 3) INTERSECT (SELECT ... LIMIT 3)` or 
* `((SELECT ... LIMIT 3) INTERSECT SELECT ... LIMIT 3)`

Is there a database that accepts this format?  If so, please say so I may parse it the same.  

Thank you

**Comment by klahnakoski** [comment]
I do recall this problem being brought up before.  Maybe a better error would help.

**Comment by klahnakoski** [comment]
better error:  https://github.com/klahnakoski/mo-sql-parsing/commit/16c7ee497393d6ea734d64b85ef675fe968b24f5#diff-6e5030d96839d3fe377cf209b6cab5b0d50ae900b458248d8c24b61774117170R73

**Comment by PosoSAgapo** [comment]
It seems like this is a wrong query, I have run the program in the SQLiteStudio with the corresponding database, then it gives the following error `Error while executing SQL query on database 'document_management': ORDER BY clause should come after INTERSECT not before`

**Comment by klahnakoski** [comment]
Thank you for checking.
