### ISSUE TITLE
Support JSON Cast Target

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#85]
Hello, it's me again :slightly_smiling_face: 

Engine/Docs: PrestoDB/Athena [Cast to JSON](https://prestodb.io/docs/current/functions/json.html#cast-to-json)

```py
fails = 'SELECT CAST(x AS JSON)'
```

It looks like it fails with any data type that the parser does not know, i.e. `FOO`. Out of curiosity: Does the parser do anything with the information which data type is the cast target, or is the validation of the data type being in some list a side effect of the parser?

Thanks again!

**Comment by klahnakoski** [comment]
The types are explicitly defined in [types.py](https://github.com/klahnakoski/mo-sql-parsing/blob/94d00f92b40f04a7b95e1415d45ca18748efca73/mo_sql_parsing/types.py#L42).  Maybe this can be expanded to any user defined type, especially in the `CAST(x AS T)` pattern.  The explicit type list is used for

* basic validation to catch typos
* limit parser while parsing infix `::` cast operator
* limit parser while parsing complex types (map, record, array, etc)

If you are interested user defined types, then some examples will help guide me on how to parse them.

Specific problem fixed here:  https://github.com/klahnakoski/mo-sql-parsing/commit/94d00f92b40f04a7b95e1415d45ca18748efca73

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.146.22081/

**Comment by sbrandtb** [comment]
@klahnakoski Thanks for the explanation. That is pretty much what I expected.

> If you are interested user defined types, then some examples will help guide me on how to parse them.

Sorry to disappoint you this time, but since Athena does not allow definig custom types (not sure if Presto can do either), I can neither provide examples, nor am I particularly interested :sweat_smile: 

However, this could possibly be a good feature for PostgreSQL since [creating custom types](https://www.postgresql.org/docs/current/sql-createtype.html) there is a pretty easy thing to do (though I am not sure how frequently this is used in the age of ORMs).
