### ISSUE TITLE
Brackets removed from subquery on formatting 

### ISSUE THREAD

**Issue by rostykob** [klahnakoski/mo-sql-parsing#87]
Hello, I discovered an issue with formatting

Let's say we have a query `"SELECT (SELECT COUNT(result)  FROM dbo.b AS B) as attr FROM dbo.table"`. It will be parsed to `{'select': {'value': {'select': {'value': {'count': 'result'}}, 'from': {'value': 'dbo.b', 'name': 'B'}}, 'name': 'attr'}, 'from': 'dbo.table'}`. But if I will format it back, it will loose the brackets `SELECT SELECT COUNT(result) FROM dbo.b AS B AS attr FROM dbo.table`. Not sure if good idea will be to introduce here a new key while parsing maybe `select_subquery` or somehow distinguish it while formatting.

**Comment by klahnakoski** [comment]
Thank you fro this report.  Looking into it now...

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/4a6355313992911c1c07ccc58e1acfa51b7b57de

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.156.22110/
