### ISSUE TITLE
parser error for columns names with quotes of As

### ISSUE THREAD

**Issue by LenaJava** [klahnakoski/mo-sql-parsing#88]
hi Support:
Could you help for a check why below query 1 is fine but query 2 with single quotes around test_col in as 'test_col' is fail? Thanks for your support.

query 1: 
 "select col1, col2, col3 as test_col from test_table where col1='col_1' and col2='col_2' and col3='col_3'"

query 2:
  "select col1, col2, col3 as 'test_col' from test_table where col1='col_1' and col2='col_2' and col3='col_3'"

Errors:

../env/lib/python3.8/site-packages/mo_sql_parsing/__init__.py:53: in parse_mysql
    return _parse(mysql_parser, sql, null, calls)
../env/lib/python3.8/site-packages/mo_sql_parsing/__init__.py:78: in _parse
    parse_result = parser.parse_string(sql, parse_all=True)
../env/lib/python3.8/site-packages/mo_parsing/core.py:78: in output
    return func(*args, **kwargs)
../env/lib/python3.8/site-packages/mo_parsing/core.py:140: in parse
    return self._parseString(string, parse_all=parse_all)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mo_parsing.core.Parser object at 0x7f880e99c850>, string = "select col1, col2, col3 as 'test_col' from test_table where col1='col_1' and col2='col_2' and col3='col_3'", parse_all = True

    def _parseString(self, string, parse_all=False):
        start = self.whitespace.skip(string, 0)
        try:
            tokens = self.element._parse(string, start)
            if parse_all:
                end = self.whitespace.skip(string, tokens.end)
                try:
                    StringEnd()._parse(string, end)
                except ParseException as pe:
                    raise ParseException(
                        self.element, 0, string, cause=tokens.failures + [pe]
                    ) from None
    
            if self.named:
                return tokens
            else:
                return tokens.tokens[0]
        except ParseException as cause:
>           raise cause.best_cause from None
E           mo_parsing.exceptions.ParseException: Expecting {,} | {from} | {union} | {intersect} | {except} | {minus} | {order by} | {offset} | {fetch} | {limit} | {union} | {intersect} | {except} | {minus} | {StringEnd}, found "as 'test_c" (at char 24), (line:1, col:25)

../env/lib/python3.8/site-packages/mo_parsing/core.py:162: ParseException

---------- coverage: platform linux, python 3.8.11-final-0 -----------

**Comment by klahnakoski** [comment]
Single quotes are string literals and can not be used for names.

**Comment by klahnakoski** [comment]
To help with this question, the parsing error has been improved to mention "identifier"

    mo_parsing.exceptions.ParseException: Expecting identifier, found "'t' from T" (at char 16), (line:1, col:17)

https://github.com/klahnakoski/mo-sql-parsing/commit/64cadf526e1b55d1e03dc6f09d2eaa9ebc2e0e8e#diff-6e5030d96839d3fe377cf209b6cab5b0d50ae900b458248d8c24b61774117170R77

new version on pypi

https://pypi.org/project/mo-sql-parsing/8.157.22117/
