### ISSUE TITLE
negative number on multiply or divide parsed incorrectly 

### ISSUE THREAD

**Issue by rostykob** [klahnakoski/mo-sql-parsing#89]
Hello Kyle!
found some small bug with parser. in query `SELECT * FROM dbo.a where ABS(a) * -1 = -22`  parsed like `{'select': '*', 'from': 'dbo.a', 'where': {'mul': [{'abs': 'a'}, '-']}}`. As you can see -1 is treated like just '-'. this is happens only on multiply or divide operations. So f.e query like `SELECT * FROM dbo.a where ABS(a) + -1 = -22` will just be parsed fine. I was able to fix it  if I would move MUL and DIV as separate entry  in keywords.py file, collection KNOWN_OPS. so it will look like 
``` 
    MOD,
    NEG,
    MUL | DIV,
    ADD | SUB,
```
Wanted to check whether it is good assumption and way to fix it

**Comment by klahnakoski** [comment]
Thank you for finding this problem, and having a fix!

I added a test, which confirms your fix is good:  https://github.com/klahnakoski/mo-sql-parsing/commit/20f316dc89780fcc96c03d0394e58b66851259fc#diff-80e67a8d8e9dd94a7299f6c160679b05f102622d182998764b6bbb466c0b633aR1727

**Comment by klahnakoski** [comment]
a couple other tests required a change: https://github.com/klahnakoski/mo-sql-parsing/commit/d55cef5d5ef73c31aa88c9e850af75673efa2d75

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.172.22121/
