### ISSUE TITLE
Sampling rows using TABLESAMPLE raises a ParseException

### ISSUE THREAD

**Issue by rbergm** [klahnakoski/mo-sql-parsing#90]
The SQL standard 2003 defined a `TABLESAMPLE` clause to execute the query only on a (random) subset of rows (supported e.g. in SQL Server and PostgreSQL). However, parsing a query which contains such a clause leads to either an incorrect JSON parse tree (if no table alias is given) or raises a `ParseException` (if an alias is given).

Consider the following example query:  `SELECT * FROM foo TABLESAMPLE bernoulli (20) WHERE a < 42`

Parsing it via `parse("SELECT * FROM foo TABLESAMPLE bernoulli (20) WHERE a < 42")` mistakes the `TABLESAMPLE` for an alias:

```python
{'select': '*',
 'from': {'value': 'foo', 'name': {'TABLESAMPLE': 'bernoulli'}},
 'where': {'lt': ['a', 42]}}
```

If the query is modified to use an alias:

`parse("SELECT * FROM foo f TABLESAMPLE bernoulli (20) WHERE f.a < 42")`,

parsing it raises a

`ParseException: Expecting {union} | {intersect} | {except} | {minus} | {order by} | {offset} | {fetch} | {limit} | {union} | {intersect} | {except} | {minus} | {StringEnd}, found "TABLESAMPL" (at char 20), (line:1, col:21)`.

EDIT [22-06-09]: I corrected a copy/paste error in the example query. If the corrected version (without parenthesis around _bernoulli_ and an added sampling percentage) is parsed, both versions (with and without table alias) raise a `ParseException`.

**Comment by klahnakoski** [comment]
These are legitimate queries?  I am trying to find the syntax definition:

https://wiki.postgresql.org/wiki/TABLESAMPLE_Implementation
https://docs.snowflake.com/en/sql-reference/constructs/sample.html

I am working on improving the TABLESAMPLE clause because there are other issues.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/80586f253ea2b326b4d5cd5d4a77d17d45bcb099#diff-e00ab716ce5b907f9837cf090cc94d2f1f84c58145be20a49fcba3f453491ff6R189

**Comment by klahnakoski** [comment]
@rbergm  I have improved the error reporting for the SQL you gave me.  If you have verified your SQL with a database, then I will spend time to install the database to explore the not-documented syntax.

Thank you for the submission!

https://pypi.org/project/mo-sql-parsing/8.183.22158/

**Comment by rbergm** [comment]
Thank you for your very quick reply! I just looked up some more specifics and found more vendor-specific differences in the precise syntax:

In the case of **Postgres**, the example queries are not valid SQL. Instead, they need to be modified like so (which I successfully tested on my local machine)

`SELECT * FROM foo TABLESAMPLE bernoulli (20) WHERE a < 42`

where _bernoulli_ describes a mandatory sampling method and 20 denotes the percentage of rows to be sampled (depending on the sampling method, see the [documentation of the `SELECT` clause](https://www.postgresql.org/docs/current/sql-select.html)).

However, in **Microsoft**'s products (e.g. SQL Server) the above example queries are perfectly valid ([documentation of the `FROM` clause](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-transact-sql?view=sql-server-ver16)). [Link to example](https://sqltest.net/#1784416)

**Oracle** does things different from the standard and uses the `SAMPLE` keyword instead of `TABLESAMPLE` (see [Feature support](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/Oracle-Support-for-Optional-Features-of-SQLFoundation2011.html#GUID-3BA98AEC-FAAD-4F21-A6AD-F696B5D36D56), Feature T613). [Link to example](https://sqltest.net/#1784410)

The Postgres way seems to be the most compliant to the actual standard, since the excerpt from SQL 2003 standard specifies it in the same manner ([linked](http://www.neilconway.org/talks/hacking/ottawa/sql_standard.pdf) at the bottom of the Postgres Wiki page, although this is no official source).

Once again, thank you for your quick reply!

**Comment by klahnakoski** [comment]
Thank you for this detailed explanation.  I am working on further enhancements, it may be a couple more days before I release again.

**Comment by klahnakoski** [comment]
@rbergm 

Using sqlfiddle (http://sqlfiddle.com/#!18/4e71b/1) I could not get your first example to parse `SELECT * FROM foo TABLESAMPLE(bernoulli) WHERE a < 42`.  The problem is "bernoulli" should not be surrounded by parenthesis. 

In any case, I was able to add oracle's `SAMPLE` variation. 

https://pypi.org/project/mo-sql-parsing/8.185.22160/

**Comment by klahnakoski** [comment]
This is done.  Feel free to open another issue if you find another problem, or even if you have a question.

Thank you for your help on this issue.
