### ISSUE TITLE
ARRAY[] is not understood

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#92]
Hello again, on Athena/PrestoDB, the empty array constructor is not understood. However, the non-empty one is understood:

```sql
-- ParseException
SELECT ARRAY[];

-- Fine
SELECT ARRAY[1];
SELECT ARRAY[1, 2];
SELECT ARRAY['1'];
SELECT ARRAY['1', '2'];
```
[Documentation](https://prestodb.io/docs/current/functions/array.html). Down in filter(), reduce() and transform() are examples for the empty array constructor.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/526d51e9a861a1878843d279329d2c2b8ef0886b

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.189.22201/
