### ISSUE TITLE
ORDER BY in Aggregates is not understood

### ISSUE THREAD

**Issue by sbrandtb** [klahnakoski/mo-sql-parsing#93]
Hello again, today we found that `ORDER BY` in aggregate functions is not understood:

```sql
-- ParserError
SELECT FOO(a ORDER BY b)

-- Fine
SELECT FOO(a)
```

[Docs](https://prestodb.io/docs/current/functions/aggregate.html) for PrestoDB/Athena.

**Comment by klahnakoski** [comment]
that looks hard.  I will think about it.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/0540c9302ea20edc4c5638407a6efa9dc7a24b64

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.189.22201/
