### ISSUE TITLE
Parsing fails when facing a column named "key"

### ISSUE THREAD

**Issue by julio-vaz** [klahnakoski/mo-sql-parsing#95]
If there is a column named "key", parsing fails.

**How to reproduce?**

Simply run a query that have "key" as the column name or alias:

```python
import mo_sql_parsing
query = "SELECT key, value FROM `a.b.c`"
mo_sql_parsing.parse(query)
```

If you change "key" to "key1", or any other name the parsing occurs as it should.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/0f888dbd5967884975af249dc0326179aedcbae8

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.189.22201/
