### ISSUE TITLE
BigQuery's REGEX r string breaks parsing

### ISSUE THREAD

**Issue by julio-vaz** [klahnakoski/mo-sql-parsing#96]
When trying to parse BigQuery's REGEX r string the parser raises an exception.

**How to reproduce?**

Try to parse any query that contains the BigQuery r string in it, either using single or double quotes.

```python
import mo_sql_parsing
query = "SELECT regex_extract(x, r'[a-z]'), value FROM `a.b.c`"
query2 = 'SELECT regex_extract(x, r"[a-z]"), value FROM `a.b.c`'
mo_sql_parsing.parse(query)
mo_sql_parsing.parse(query2)
```

You can check [BigQuery's doc](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_extract) to better understand how r string works but it's pretty similar to how Python does it.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/6abf9a0908b1a61d9a28515ec49cf051615a645e

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.189.22201/
