### ISSUE TITLE
Parser does not support BigQuery's SAFE_CAST function

### ISSUE THREAD

**Issue by julio-vaz** [klahnakoski/mo-sql-parsing#97]
When parsing queries that contains a call to [BigQuery's SAFE_CAST function](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#safe_casting) the parser raises an exception.

**How to reproduce?**

Run any query that contains a SAFE_CAST function call:

```python
import mo_sql_parsing
query = "SELECT SAFE_CAST(x AS STRING) from `a.b.c`"
mo_sql_parsing.parse(query)
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/679d47486e6d570e89748880e3fb7e039285b889

**Comment by klahnakoski** [comment]
tests were not working, fixed: https://github.com/klahnakoski/mo-sql-parsing/commit/0540c9302ea20edc4c5638407a6efa9dc7a24b64#diff-028acb5a76624487a6dfd257ba58d641b4a84b95750894e2d5e0e9005032c7f3L429-L432

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.189.22201/
