### ISSUE TITLE
Parser does not support SELECT e UNNEST(y) AS x patten

### ISSUE THREAD

**Issue by julio-vaz** [klahnakoski/mo-sql-parsing#98]
If you execute a query that contains a INTERVAL expression that references a variable as the `int64_expression` part, the parser breaks.

**How to reproduce?**

We can reproduce by running a query that generates a time series based on a timestamp value through the parser:

```python
import mo_sql_parsing
query = "SELECT timestamp_add('2022-07-14T12:42:11Z', INTERVAL x MINUTE) UNNEST(GENERATE_ARRAY(1, 10)) as x"
mo_sql_parsing.parse(query)
```

This is the output of this query in BigQuery:

```json
[{
  "f0_": "2022-07-14T12:43:11Z"
}, {
  "f0_": "2022-07-14T12:44:11Z"
}, {
  "f0_": "2022-07-14T12:45:11Z"
}, {
  "f0_": "2022-07-14T12:46:11Z"
}, {
  "f0_": "2022-07-14T12:47:11Z"
}, {
  "f0_": "2022-07-14T12:48:11Z"
}, {
  "f0_": "2022-07-14T12:49:11Z"
}, {
  "f0_": "2022-07-14T12:50:11Z"
}, {
  "f0_": "2022-07-14T12:51:11Z"
}, {
  "f0_": "2022-07-14T12:52:11Z"
}]
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/f656b97ed6e1d3d7dc6e6b865e2f55e739b6954a

but more work to do.  I have not seen the  `SELECT e UNNEST(y) AS x` pattern yet

**Comment by julio-vaz** [comment]
Thank you for all the fixes!!! It was almost enough to parse my queries without errors. The only problem I'm currently facing is the lack of BIGNUMERIC support that I tried to introduce with [this pull request](https://github.com/klahnakoski/mo-sql-parsing/pull/94). Did you had the time to review it?

**Comment by klahnakoski** [comment]
merged https://github.com/klahnakoski/mo-sql-parsing/pull/94
