### ISSUE TITLE
BigQuery's SELECT * EXCEPT statement breaks parser

### ISSUE THREAD

**Issue by julio-vaz** [klahnakoski/mo-sql-parsing#99]
BigQuery [SELECT * EXCEPT statements](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_except) are not supported by the parser and causes it to raise an exception.

**How to reproduce?**

Run a query with SELECT * EXCEPT:

```python
import mo_sql_parsing
query = "SELECT * EXCEPT(x) FROM `a.b.c`"
mo_sql_parsing.parse(query)
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/8a2f1b786895c9606c3d6a238565450e8d98b5c5

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.189.22201/
